/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interaz;

import java.awt.event.KeyEvent;

/**
 *
 * 
 */
public class DialogoOpcion extends javax.swing.JDialog {
    private static boolean aceptar=false; private boolean comentario = false;
    public static final int ICONO_ERROR = 1;
    public static final int ICONO_INFORMACION = 2;
    public static final int ICONO_INTERROGANTE = 3;
    public static final int ICONO_INTERROGANTE_DESCRIPCION = 4;
    public static final int ICONO_INFORMACION_DESCRIPCION = 5;
    public static String titulo="",mensaje="";
    /**
     * Creates new form DialogoOpcion
     */
    public DialogoOpcion(java.awt.Frame parent, boolean modal, int icono, String titulo, String mensaje) {
        super(parent, modal);
        initComponents();
        lbl_Titulo.setText(titulo);
        jTextArea1.setText(mensaje);
        this.titulo=titulo;
        this.mensaje=mensaje;
        cargar_icono(icono);
        this.setLocationRelativeTo(null);
        btn_Aceptar.requestFocus();
        txt_Filtro.setVisible(icono == 4);
        
        
    }
    public DialogoOpcion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * Metodo que carga el icono del panel en base a un numero entero
     * @param Icono numero del icono
     */
    private void cargar_icono(int Icono)
    {
        switch (Icono) {
            case 1:
                this.Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/error.png")));
                this.btn_Cancelar.setVisible(false);
                break;
            case 2:
                this.Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/info.png")));
                this.btn_Cancelar.setVisible(false);
                break;
            case 4:
                this.Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/question.png")));
                this.btn_Cancelar.setVisible(true);
                comentario = true;
                break;
            case 5:
                this.Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/info.png")));
                this.btn_Cancelar.setVisible(true);
                comentario = true;
                break;
            default:
                this.Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/question.png")));
                this.btn_Cancelar.setVisible(true);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jPanel1 = new javax.swing.JPanel();
        btn_Cancelar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_Titulo = new javax.swing.JLabel();
        Salir1 = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        btn_Aceptar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txt_Filtro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(96, 96, 96), 1, true));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Cancelar.setBackground(new java.awt.Color(255, 51, 51));
        btn_Cancelar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setOpaque(true);
        btn_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 100, 27));

        jPanel2.setBackground(new java.awt.Color(96, 96, 96));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        lbl_Titulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Titulo.setText("TITULO");

        Salir1.setBackground(new java.awt.Color(96, 96, 96));
        Salir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/cancel (2).png"))); // NOI18N
        Salir1.setOpaque(true);
        Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Salir1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lbl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/info.png"))); // NOI18N
        jPanel1.add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btn_Aceptar.setBackground(new java.awt.Color(255, 51, 51));
        btn_Aceptar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Aceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.setNextFocusableComponent(btn_Cancelar);
        btn_Aceptar.setOpaque(true);
        btn_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AceptarMouseClicked(evt);
            }
        });
        btn_Aceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_AceptarKeyReleased(evt);
            }
        });
        jPanel1.add(btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 27));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(64, 64, 64));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(64, 64, 64));
        jTextArea1.setDisabledTextColor(new java.awt.Color(64, 64, 64));
        jTextArea1.setEnabled(false);
        jTextArea1.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        jTextArea1.setSelectionColor(new java.awt.Color(192, 192, 192));
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 290, 60));

        txt_Filtro.setBackground(new java.awt.Color(240, 240, 240));
        txt_Filtro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_Filtro.setForeground(new java.awt.Color(64, 64, 64));
        txt_Filtro.setText("Ingrese un comentario");
        txt_Filtro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_Filtro.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Filtro.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_Filtro.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_Filtro.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_Filtro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FiltroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FiltroFocusLost(evt);
            }
        });
        txt_Filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FiltroActionPerformed(evt);
            }
        });
        txt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 290, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
    *funcion booleana que retorna el valor de la opcion elegida en el cuadro de dialogo     
    * @return TRUE si se clickeo aceptar - FALSE si se cerro o se clickeo cancelar
    */
    public boolean isAceptar() {
        return aceptar;
    }

    private void btn_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_CancelarMouseClicked

    private void btn_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AceptarMouseClicked
        // TODO add your handling code here:
        if (!comentario) {
            aceptar=true;
            this.setVisible(false);
        }else{
            if (!txt_Filtro.getText().equals("INGRESE UN COMENTARIO") && !txt_Filtro.getText().equals("")) {
                aceptar=true;
                Coment = txt_Filtro.getText();
                System.out.println(Coment);
                this.setVisible(false);
            }else{
                DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "ERROR", "INGRESE UN COMENTARIO");
                dialogo.setVisible(true);
            }
        }

    }//GEN-LAST:event_btn_AceptarMouseClicked

    private void Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_Salir1MouseClicked
    private String Coment = "";

    public String getComent() {
        return Coment;
    }
    
    private void btn_AceptarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_AceptarKeyReleased
        int codigo=evt.getKeyCode();
        if(codigo==KeyEvent.VK_ENTER||codigo==KeyEvent.VK_SPACE){
            if (!comentario) {
                aceptar=true;
                this.setVisible(false);
            }else{
                if (!txt_Filtro.getText().equals("INGRESE UN COMENTARIO") && !txt_Filtro.getText().equals("")) {
                    aceptar=true;
                    Coment = txt_Filtro.getText();
                    this.setVisible(false);
                }else{
                    DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "ERROR", "INGRESE UN COMENTARIO");
                    dialogo.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btn_AceptarKeyReleased

    private void txt_FiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyPressed

    }//GEN-LAST:event_txt_FiltroKeyPressed

    private void txt_FiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FiltroActionPerformed

    private void txt_FiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FiltroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FiltroFocusLost

    private void txt_FiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FiltroFocusGained
        txt_Filtro.selectAll();
    }//GEN-LAST:event_txt_FiltroFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogoOpcion dialog;
                dialog = new DialogoOpcion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel Salir1;
    private javax.swing.JLabel btn_Aceptar;
    private javax.swing.JLabel btn_Cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_Titulo;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField txt_Filtro;
    // End of variables declaration//GEN-END:variables
}
