/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interaz;

import Excepciones.NoSePuedeConectar;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import clases.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * 
 */
public class NuevoProducto extends javax.swing.JPanel {
    private Base conexion=new Base();
    private ArrayList[] sucursales_unidades;
    private ArrayList productoActual=new ArrayList(); 
    private boolean nuevo=false;
    private boolean modificar=false;
    Color color_reset = new Color(96,96,96);
    Color color_set = new Color(128,128,128);
    Color color_naranja = new Color(255,102,102);
    Color color_rojo = new Color(255,51,51);
    Color color_blanco = new Color(250,250,250);
    CaracteristicasProxy proxy;

    public NuevoProducto(Base conexion) {
        initComponents();
//        pnContenido1.setVisible(false);
        this.conexion=conexion;
        buttonGroup1.add(rbtn_Credito);
        buttonGroup1.add(rbtn_Credito1);
        buttonGroup1.add(rbtn_Credito2);
        btn_Cancelar.setVisible(false);
        try {
            sucursales_unidades=new ArrayList[2];
            cmb_sucursal.addItem("Total");
            sucursales_unidades=conexion.obtener_Sucursales_Unidades();
            for(int i=0; i<sucursales_unidades[0].size();i++)
            {
                cmb_sucursal.addItem(sucursales_unidades[1].get(i).toString());
            }
            for(int i=0; i<sucursales_unidades[2].size();i++)
            {
                cmb_unidad.addItem(sucursales_unidades[3].get(i).toString());
            }
            cmb_unidad.addItem("Ninguno");
            cmb_unidad.setSelectedIndex(cmb_unidad.getItemCount()-1);
            cambiarModo();
            llenarListado();
            setJTexFieldChanged(txt_codigo1);
            scp_listado.getViewport().setBackground(color_blanco);
        } catch (SQLException|NoSePuedeConectar ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        proxy = new CaracteristicasProxy();
        ArrayList<String> caract = proxy.getCaracteristicas();
        DefaultTableModel modeloProp = (DefaultTableModel) jTable1.getModel();
        for (String c:caract){
            modeloProp.addRow(new Object[]{c,""});
        }
        switch(conexion.getUsuario().getIdPermisos()){
            case 3:
                btn_nuevo.setEnabled(false);
                btn_modificar.setEnabled(false);
                btn_eliminar.setEnabled(false);
                break;
            case 4:
                btn_nuevo.setEnabled(false);
                btn_modificar.setEnabled(false);
                btn_eliminar.setEnabled(false);
//                btn_ver.setEnabled(false);
                break;
            case 5:
                btn_nuevo.setEnabled(false);
                btn_modificar.setEnabled(false);
                btn_eliminar.setEnabled(false);
                break;
            case 6:
                btn_nuevo.setEnabled(false);
                btn_modificar.setEnabled(false);
                btn_eliminar.setEnabled(false);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnContenido = new javax.swing.JPanel();
        pnDetalle = new javax.swing.JPanel();
        lbl_Titulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_codigoBarra = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        lbl_precioVenta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_codigoBarra = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_estanteria = new javax.swing.JTextField();
        txt_columna = new javax.swing.JTextField();
        txt_fila = new javax.swing.JTextField();
        txt_existencia = new javax.swing.JTextField();
        cmb_unidad = new javax.swing.JComboBox<>();
        cmb_sucursal = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        scp_descripcion = new javax.swing.JScrollPane();
        txa_descripcion = new javax.swing.JTextArea();
        btn_Guardar_Aceptar = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        scp_listado = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        rbtn_Credito = new javax.swing.JRadioButton();
        rbtn_Credito1 = new javax.swing.JRadioButton();
        rbtn_Credito2 = new javax.swing.JRadioButton();
        txt_codigo1 = new javax.swing.JTextField();
        lbl_codigo1 = new javax.swing.JLabel();
        ftx_costo = new javax.swing.JFormattedTextField();
        ftx_venta = new javax.swing.JFormattedTextField();
        btn_Cancelar = new javax.swing.JLabel();
        btn_Guardar_Aceptar1 = new javax.swing.JLabel();
        btn_Guardar_Aceptar2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Guardar_Aceptar3 = new javax.swing.JLabel();
        btn_Guardar_Aceptar4 = new javax.swing.JLabel();
        pn_herramientas = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();
        Salir1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64)));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(939, 649));
        setMinimumSize(new java.awt.Dimension(939, 649));
        setName("detallesPN"); // NOI18N
        setPreferredSize(new java.awt.Dimension(940, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnContenido.setMinimumSize(new java.awt.Dimension(150, 150));
        pnContenido.setPreferredSize(new java.awt.Dimension(840, 650));

        pnDetalle.setForeground(new java.awt.Color(64, 64, 64));
        pnDetalle.setAlignmentX(0.0F);
        pnDetalle.setAlignmentY(0.0F);
        pnDetalle.setMaximumSize(new java.awt.Dimension(150, 150));
        pnDetalle.setMinimumSize(new java.awt.Dimension(150, 150));
        pnDetalle.setPreferredSize(new java.awt.Dimension(900, 650));

        lbl_Titulo.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Titulo.setText("PRODUCTOS");

        jSeparator2.setBackground(new java.awt.Color(64, 64, 64));
        jSeparator2.setForeground(new java.awt.Color(64, 64, 64));

        lbl_codigoBarra.setBackground(new java.awt.Color(64, 64, 64));
        lbl_codigoBarra.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_codigoBarra.setForeground(new java.awt.Color(64, 64, 64));
        lbl_codigoBarra.setText("Código de barras");

        lbl_codigo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_codigo.setForeground(new java.awt.Color(64, 64, 64));
        lbl_codigo.setText("Código");
        lbl_codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_codigoMouseClicked(evt);
            }
        });

        lbl_precioVenta.setBackground(new java.awt.Color(64, 64, 64));
        lbl_precioVenta.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_precioVenta.setForeground(new java.awt.Color(64, 64, 64));
        lbl_precioVenta.setText("Precio venta");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(64, 64, 64));
        jLabel8.setText("Descripción");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(64, 64, 64));
        jLabel10.setText("Precio costo");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(64, 64, 64));
        jLabel11.setText("Columna");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(64, 64, 64));
        jLabel12.setText("Fila");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 64, 64));
        jLabel13.setText("Marca");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(64, 64, 64));
        jLabel14.setText("Existencias");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(64, 64, 64));
        jLabel15.setText("Sucursal");

        txt_codigo.setBackground(new java.awt.Color(250, 250, 250));
        txt_codigo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_codigo.setForeground(new java.awt.Color(64, 64, 64));
        txt_codigo.setText("No disponible");
        txt_codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        txt_codigo.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_codigo.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_codigo.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_codigo.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_codigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigoFocusLost(evt);
            }
        });
        txt_codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_codigoMousePressed(evt);
            }
        });
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });

        txt_codigoBarra.setBackground(new java.awt.Color(250, 250, 250));
        txt_codigoBarra.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_codigoBarra.setForeground(new java.awt.Color(64, 64, 64));
        txt_codigoBarra.setText("No disponible");
        txt_codigoBarra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        txt_codigoBarra.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_codigoBarra.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_codigoBarra.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_codigoBarra.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_codigoBarra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_codigoBarraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigoBarraFocusLost(evt);
            }
        });
        txt_codigoBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_codigoBarraMousePressed(evt);
            }
        });
        txt_codigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoBarraActionPerformed(evt);
            }
        });

        txt_marca.setBackground(new java.awt.Color(250, 250, 250));
        txt_marca.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_marca.setForeground(new java.awt.Color(64, 64, 64));
        txt_marca.setText("No disponible");
        txt_marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        txt_marca.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_marca.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_marca.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_marca.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_marcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_marcaFocusLost(evt);
            }
        });
        txt_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_marcaMousePressed(evt);
            }
        });
        txt_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marcaActionPerformed(evt);
            }
        });

        txt_estanteria.setBackground(new java.awt.Color(250, 250, 250));
        txt_estanteria.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_estanteria.setForeground(new java.awt.Color(64, 64, 64));
        txt_estanteria.setText("No disponible");
        txt_estanteria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        txt_estanteria.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_estanteria.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_estanteria.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_estanteria.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_estanteria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_estanteriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_estanteriaFocusLost(evt);
            }
        });
        txt_estanteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_estanteriaMousePressed(evt);
            }
        });
        txt_estanteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estanteriaActionPerformed(evt);
            }
        });

        txt_columna.setBackground(new java.awt.Color(250, 250, 250));
        txt_columna.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_columna.setForeground(new java.awt.Color(64, 64, 64));
        txt_columna.setText("No disponible");
        txt_columna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        txt_columna.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_columna.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_columna.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_columna.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_columna.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_columnaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_columnaFocusLost(evt);
            }
        });
        txt_columna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_columnaMousePressed(evt);
            }
        });
        txt_columna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_columnaActionPerformed(evt);
            }
        });

        txt_fila.setBackground(new java.awt.Color(250, 250, 250));
        txt_fila.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_fila.setForeground(new java.awt.Color(64, 64, 64));
        txt_fila.setText("No disponible");
        txt_fila.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        txt_fila.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_fila.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_fila.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_fila.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_fila.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_filaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_filaFocusLost(evt);
            }
        });
        txt_fila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_filaMousePressed(evt);
            }
        });
        txt_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filaActionPerformed(evt);
            }
        });

        txt_existencia.setBackground(new java.awt.Color(250, 250, 250));
        txt_existencia.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_existencia.setForeground(new java.awt.Color(64, 64, 64));
        txt_existencia.setText("No disponible");
        txt_existencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        txt_existencia.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_existencia.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_existencia.setNextFocusableComponent(btn_Guardar_Aceptar);
        txt_existencia.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_existencia.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_existencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_existenciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_existenciaFocusLost(evt);
            }
        });
        txt_existencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_existenciaMousePressed(evt);
            }
        });
        txt_existencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_existenciaActionPerformed(evt);
            }
        });

        cmb_unidad.setBackground(new java.awt.Color(250, 250, 250));
        cmb_unidad.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cmb_unidad.setForeground(new java.awt.Color(64, 64, 64));
        cmb_unidad.setBorder(null);
        cmb_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_unidadActionPerformed(evt);
            }
        });

        cmb_sucursal.setBackground(new java.awt.Color(250, 250, 250));
        cmb_sucursal.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cmb_sucursal.setForeground(new java.awt.Color(64, 64, 64));
        cmb_sucursal.setBorder(null);
        cmb_sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sucursalActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(64, 64, 64));
        jLabel16.setText("Estantería");

        txa_descripcion.setBackground(new java.awt.Color(250, 250, 250));
        txa_descripcion.setColumns(20);
        txa_descripcion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txa_descripcion.setForeground(new java.awt.Color(64, 64, 64));
        txa_descripcion.setLineWrap(true);
        txa_descripcion.setRows(5);
        txa_descripcion.setBorder(null);
        txa_descripcion.setCaretColor(new java.awt.Color(64, 64, 64));
        txa_descripcion.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txa_descripcion.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txa_descripcion.setSelectionColor(new java.awt.Color(192, 192, 192));
        scp_descripcion.setViewportView(txa_descripcion);

        btn_Guardar_Aceptar.setBackground(new java.awt.Color(255, 51, 51));
        btn_Guardar_Aceptar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Guardar_Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar_Aceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Guardar_Aceptar.setText("Guardar");
        btn_Guardar_Aceptar.setName(""); // NOI18N
        btn_Guardar_Aceptar.setOpaque(true);
        btn_Guardar_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Guardar_AceptarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Guardar_AceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Guardar_AceptarMouseReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(64, 64, 64));
        jLabel17.setText("Unidades");

        scp_listado.setBackground(new java.awt.Color(250, 250, 250));
        scp_listado.setBorder(null);
        scp_listado.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scp_listado.setPreferredSize(new java.awt.Dimension(292, 615));

        tbl_productos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tbl_productos.setForeground(new java.awt.Color(64, 64, 64));
        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_productos.setAutoscrolls(false);
        tbl_productos.setGridColor(new java.awt.Color(64, 64, 64));
        tbl_productos.setSelectionBackground(new java.awt.Color(192, 192, 192));
        tbl_productos.setSelectionForeground(new java.awt.Color(64, 64, 64));
        tbl_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productosMouseClicked(evt);
            }
        });
        scp_listado.setViewportView(tbl_productos);

        rbtn_Credito.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        rbtn_Credito.setForeground(new java.awt.Color(64, 64, 64));
        rbtn_Credito.setSelected(true);
        rbtn_Credito.setText("Código");
        rbtn_Credito.setBorder(null);
        rbtn_Credito.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn_CreditoStateChanged(evt);
            }
        });
        rbtn_Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_CreditoActionPerformed(evt);
            }
        });

        rbtn_Credito1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        rbtn_Credito1.setForeground(new java.awt.Color(64, 64, 64));
        rbtn_Credito1.setSelected(true);
        rbtn_Credito1.setText("Barras");
        rbtn_Credito1.setBorder(null);
        rbtn_Credito1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn_Credito1StateChanged(evt);
            }
        });

        rbtn_Credito2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        rbtn_Credito2.setForeground(new java.awt.Color(64, 64, 64));
        rbtn_Credito2.setSelected(true);
        rbtn_Credito2.setText("Descripción");
        rbtn_Credito2.setBorder(null);
        rbtn_Credito2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn_Credito2StateChanged(evt);
            }
        });
        rbtn_Credito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Credito2ActionPerformed(evt);
            }
        });

        txt_codigo1.setBackground(new java.awt.Color(250, 250, 250));
        txt_codigo1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_codigo1.setForeground(new java.awt.Color(64, 64, 64));
        txt_codigo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        txt_codigo1.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_codigo1.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        txt_codigo1.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_codigo1.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_codigo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_codigo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigo1FocusLost(evt);
            }
        });
        txt_codigo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_codigo1MousePressed(evt);
            }
        });
        txt_codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigo1ActionPerformed(evt);
            }
        });

        lbl_codigo1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_codigo1.setForeground(new java.awt.Color(64, 64, 64));
        lbl_codigo1.setText("Filtro");
        lbl_codigo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_codigo1MouseClicked(evt);
            }
        });

        ftx_costo.setBackground(new java.awt.Color(250, 250, 250));
        ftx_costo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        ftx_costo.setForeground(new java.awt.Color(64, 64, 64));
        ftx_costo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        ftx_costo.setCaretColor(new java.awt.Color(64, 64, 64));
        ftx_costo.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        ftx_costo.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        ftx_costo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        ftx_costo.setPreferredSize(new java.awt.Dimension(271, 16));
        ftx_costo.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        ftx_costo.setSelectionColor(new java.awt.Color(192, 192, 192));
        ftx_costo.setValue(0);
        ftx_costo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftx_costoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftx_costoFocusLost(evt);
            }
        });

        ftx_venta.setBackground(new java.awt.Color(250, 250, 250));
        ftx_venta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 185, 185)));
        ftx_venta.setForeground(new java.awt.Color(64, 64, 64));
        ftx_venta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        ftx_venta.setCaretColor(new java.awt.Color(64, 64, 64));
        ftx_venta.setDisabledTextColor(new java.awt.Color(96, 96, 96));
        ftx_venta.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        ftx_venta.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        ftx_venta.setPreferredSize(new java.awt.Dimension(271, 16));
        ftx_venta.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        ftx_venta.setSelectionColor(new java.awt.Color(192, 192, 192));
        ftx_venta.setValue(0);
        ftx_venta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftx_ventaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftx_ventaFocusLost(evt);
            }
        });

        btn_Cancelar.setBackground(new java.awt.Color(255, 51, 51));
        btn_Cancelar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setName(""); // NOI18N
        btn_Cancelar.setOpaque(true);
        btn_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CancelarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_CancelarMouseReleased(evt);
            }
        });

        btn_Guardar_Aceptar1.setBackground(new java.awt.Color(255, 51, 51));
        btn_Guardar_Aceptar1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Guardar_Aceptar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar_Aceptar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Guardar_Aceptar1.setText(">");
        btn_Guardar_Aceptar1.setName(""); // NOI18N
        btn_Guardar_Aceptar1.setOpaque(true);
        btn_Guardar_Aceptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar1MouseReleased(evt);
            }
        });

        btn_Guardar_Aceptar2.setBackground(new java.awt.Color(255, 51, 51));
        btn_Guardar_Aceptar2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Guardar_Aceptar2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar_Aceptar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Guardar_Aceptar2.setText("<");
        btn_Guardar_Aceptar2.setName(""); // NOI18N
        btn_Guardar_Aceptar2.setOpaque(true);
        btn_Guardar_Aceptar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar2MouseReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Propiedad", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_Guardar_Aceptar3.setBackground(new java.awt.Color(255, 51, 51));
        btn_Guardar_Aceptar3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Guardar_Aceptar3.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar_Aceptar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Guardar_Aceptar3.setText("+");
        btn_Guardar_Aceptar3.setName(""); // NOI18N
        btn_Guardar_Aceptar3.setOpaque(true);
        btn_Guardar_Aceptar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar3MouseReleased(evt);
            }
        });

        btn_Guardar_Aceptar4.setBackground(new java.awt.Color(255, 51, 51));
        btn_Guardar_Aceptar4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Guardar_Aceptar4.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar_Aceptar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Guardar_Aceptar4.setText("-");
        btn_Guardar_Aceptar4.setName(""); // NOI18N
        btn_Guardar_Aceptar4.setOpaque(true);
        btn_Guardar_Aceptar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Guardar_Aceptar4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnDetalleLayout = new javax.swing.GroupLayout(pnDetalle);
        pnDetalle.setLayout(pnDetalleLayout);
        pnDetalleLayout.setHorizontalGroup(
            pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetalleLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetalleLayout.createSequentialGroup()
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_precioVenta)
                            .addComponent(jLabel13)
                            .addComponent(lbl_codigo)
                            .addComponent(jLabel11)
                            .addComponent(txt_columna, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ftx_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txt_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_codigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_codigoBarra)
                                    .addComponent(jLabel10)
                                    .addComponent(ftx_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmb_sucursal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_fila, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                        .addComponent(txt_estanteria, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(txt_existencia, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(scp_descripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Guardar_Aceptar3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Guardar_Aceptar4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(90, 90, 90)
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDetalleLayout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(btn_Guardar_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_codigo1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetalleLayout.createSequentialGroup()
                                        .addComponent(rbtn_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(rbtn_Credito2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                        .addComponent(rbtn_Credito1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(scp_listado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_codigo1)))
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addComponent(btn_Guardar_Aceptar2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Guardar_Aceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(pnDetalleLayout.createSequentialGroup()
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Titulo)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnDetalleLayout.setVerticalGroup(
            pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetalleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_Titulo)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetalleLayout.createSequentialGroup()
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_codigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetalleLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_Credito)
                                    .addComponent(rbtn_Credito1)
                                    .addComponent(rbtn_Credito2))
                                .addGap(18, 18, 18)
                                .addComponent(scp_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetalleLayout.createSequentialGroup()
                                .addComponent(lbl_precioVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ftx_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftx_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_estanteria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(3, 3, 3)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_columna, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_existencia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(cmb_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scp_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(pnDetalleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_codigo)
                            .addComponent(lbl_codigoBarra)
                            .addComponent(lbl_codigo1))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetalleLayout.createSequentialGroup()
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Guardar_Aceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Guardar_Aceptar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Guardar_Aceptar3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Guardar_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Guardar_Aceptar4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout pnContenidoLayout = new javax.swing.GroupLayout(pnContenido);
        pnContenido.setLayout(pnContenidoLayout);
        pnContenidoLayout.setHorizontalGroup(
            pnContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContenidoLayout.createSequentialGroup()
                .addComponent(pnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnContenidoLayout.setVerticalGroup(
            pnContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContenidoLayout.createSequentialGroup()
                .addComponent(pnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(pnContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 41, 935, 645));

        pn_herramientas.setBackground(new java.awt.Color(96, 96, 96));
        pn_herramientas.setPreferredSize(new java.awt.Dimension(868, 40));
        pn_herramientas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nuevo.setBackground(new java.awt.Color(96, 96, 96));
        btn_nuevo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_nuevo.setText("NUEVO");
        btn_nuevo.setName(""); // NOI18N
        btn_nuevo.setOpaque(true);
        btn_nuevo.setPreferredSize(new java.awt.Dimension(93, 40));
        btn_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseClicked(evt);
            }
        });
        pn_herramientas.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, -1));

        btn_modificar.setBackground(new java.awt.Color(96, 96, 96));
        btn_modificar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificar.setText(" MODIFICAR");
        btn_modificar.setName(""); // NOI18N
        btn_modificar.setOpaque(true);
        btn_modificar.setPreferredSize(new java.awt.Dimension(93, 40));
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });
        pn_herramientas.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 138, -1));

        btn_eliminar.setBackground(new java.awt.Color(96, 96, 96));
        btn_eliminar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.setName(""); // NOI18N
        btn_eliminar.setOpaque(true);
        btn_eliminar.setPreferredSize(new java.awt.Dimension(93, 40));
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        pn_herramientas.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 138, -1));

        Salir1.setBackground(new java.awt.Color(96, 96, 96));
        Salir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/cancel (2).png"))); // NOI18N
        Salir1.setOpaque(true);
        Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir1MouseClicked(evt);
            }
        });
        pn_herramientas.add(Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 40, 40));

        add(pn_herramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 940, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
    private void llenarListado()
    {
            try {
            int filtro;
            if(rbtn_Credito.isSelected())
                filtro=0;
            else if(rbtn_Credito1.isSelected())
                filtro=1;
            else
                filtro=2;
            
            DefaultTableModel tabla=conexion.obtenerProductos_vista(filtro,txt_codigo1.getText());
            if(tabla!=null)
                    tbl_productos.setModel(tabla);
                    /*//if(!nuevo){
                    ArrayList[] listado=null;
                    try {
                    listado=conexion.obtener_productos();
                    } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(listado!=null)
                    {
                    pn_listado.removeAll();
                    for(int i=0;i<listado[0].size();i++)
                    {
                    JPanel pan=new producto_lista(listado[1].get(i).toString(),listado[2].get(i).toString(),
                    listado[3].get(i).toString(),this);
                    pan.setSize(292,100);
                    pan.setLocation(0, i*100);
                    pan.setName(listado[0].get(i).toString());
                    pn_listado.add(pan);
                    }
                    pn_listado.setPreferredSize(new Dimension(pn_listado.getParent().getWidth(),listado[0].size()*100));
                    pn_listado.getParent().revalidate();
                    pn_listado.getParent().repaint();
                    }
                    //}*/
        } catch (SQLException|NoSePuedeConectar ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }           
    }    
    
    private void cambiarModo(){
        txt_codigo.setEnabled(nuevo);      
        txt_columna.setEnabled(nuevo||modificar);
        ftx_costo.setEnabled(nuevo||modificar);
        txt_estanteria.setEnabled(nuevo||modificar);
        txt_existencia.setEnabled(nuevo);
        txt_fila.setEnabled(nuevo||modificar);
        txt_marca.setEnabled(nuevo||modificar);
        ftx_venta.setEnabled(nuevo||modificar);
        txa_descripcion.setEnabled(nuevo||modificar);  
        btn_Guardar_Aceptar.setVisible(nuevo||modificar);
        txt_codigoBarra.setEnabled(nuevo||modificar);
        cmb_sucursal.setEnabled(nuevo || !modificar);
        tbl_productos.setEnabled(!nuevo);
        cmb_unidad.setEnabled(true);
    }
    public void cargarProducto(int i)
    {
        try {
            productoActual=conexion.obtener_detalleProducto(i,0);
        } catch (SQLException|NoSePuedeConectar ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(productoActual.size()>0)
            cargarProductoActual();
        else
            modoSinDatos();
    }
    public void cargarProducto(String codigo, String codigo_barras, String descripcion)
    {
        try {
            productoActual=conexion.obtener_detalleProducto(descripcion,codigo,codigo_barras);
        } catch (SQLException|NoSePuedeConectar ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(productoActual.size()>0)
            cargarProductoActual();
        else
           modoSinDatos();
    }
    private void cargarProductoActual()
    {
        if(productoActual.size()>0 && !nuevo){
            try {
                txt_codigo.setText(productoActual.get(1).toString());
                txt_codigoBarra.setText(productoActual.get(2).toString());
                txa_descripcion.setText(productoActual.get(3).toString());
                ftx_venta.setValue(Double.parseDouble(productoActual.get(4).toString()));
                ftx_venta.setText("Q"+String.format("%.2f",Double.parseDouble(productoActual.get(4).toString())));
                 ftx_costo.setValue(Double.parseDouble(productoActual.get(5).toString()));
                ftx_costo.setText("Q"+String.format("%.2f",Double.parseDouble(productoActual.get(5).toString())));
                if(productoActual.get(6)==null)
                    txt_estanteria.setText("");
                else
                    txt_estanteria.setText(productoActual.get(6).toString());
                if(productoActual.get(7)==null)
                    txt_columna.setText("");
                else
                    txt_columna.setText(productoActual.get(7).toString());
                if(productoActual.get(8)==null)
                    txt_fila.setText("");
                else
                    txt_fila.setText(productoActual.get(8).toString());
                if(productoActual.get(9)==null)
                {
                    cmb_unidad.setSelectedIndex(cmb_unidad.getItemCount()-1);
                    cmb_unidad.setEnabled(false);
                }
                else
                {
                    cmb_unidad.setSelectedIndex(Integer.parseInt(productoActual.get(9).toString())-1);
                    cmb_unidad.setEnabled(true);
                }
                if(productoActual.get(10)==null)
                    txt_fila.setText("");
                else
                    txt_marca.setText(productoActual.get(10).toString());
                    cmb_sucursal.setSelectedIndex(0);
                    txt_existencia.setText(conexion.obtenerExistencia(0, Integer.parseInt(productoActual.get(0).toString()))+"");
                    } catch (SQLException ex) {
                Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSePuedeConectar ex) {
                Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
        else
            modoSinDatos();
    }
    private void modoDeshabilitado()
    {
        txt_marca.setText("");
        txt_columna.setText("");
        ftx_costo.setValue(0.00);
        ftx_costo.setText("Q0.00");
        txt_codigoBarra.setText("");
        txt_existencia.setText("");
        txt_fila.setText("");
        ftx_venta.setValue(0.00);
        ftx_venta.setText("Q0.00");
        txt_codigo.setText("");
        txa_descripcion.setText("");
        txt_estanteria.setText("");
    }
    
    private void modoSinDatos()
    {
        txt_marca.setText("");
        txt_columna.setText("");
        ftx_costo.setValue(0.00);
        ftx_costo.setText("Q0.00");
        txt_codigoBarra.setText("");
        txt_existencia.setText("");
        txt_fila.setText("");
        ftx_venta.setValue(0.00);
        ftx_venta.setText("Q0.00");
        txt_codigo.setText("");
        txa_descripcion.setText("");
        txt_estanteria.setText("");
    }
    private void setJTexFieldChanged(JTextField txt)
    {
        DocumentListener documentListener = new DocumentListener() {
        @Override
        public void changedUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void insertUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void removeUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }

        };
        txt.getDocument().addDocumentListener(documentListener);
    }
        private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
            txt_filtroChanged();
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
            txt_filtroChanged();
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            txt_filtroChanged();
        }
    }
    private void txt_filtroChanged()
    {
        //Copiar el contenido del jtextfield al jlabel
        llenarListado();
    }
    private void txt_columnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_columnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_columnaActionPerformed

    private void txt_columnaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_columnaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_columnaMousePressed

    private void txt_columnaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_columnaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_columnaFocusLost

    private void txt_columnaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_columnaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_columnaFocusGained

    private void txt_codigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoBarraActionPerformed

    private void txt_codigoBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_codigoBarraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoBarraMousePressed

    private void txt_codigoBarraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoBarraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoBarraFocusLost

    private void txt_codigoBarraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoBarraFocusGained
        // TODO add your handling code here:   
    }//GEN-LAST:event_txt_codigoBarraFocusGained

    private void txt_filaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_filaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filaFocusGained

    private void txt_filaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_filaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filaFocusLost

    private void txt_filaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_filaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filaMousePressed

    private void txt_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filaActionPerformed

    private void txt_marcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_marcaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaFocusGained

    private void txt_marcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_marcaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaFocusLost

    private void txt_marcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_marcaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaMousePressed

    private void txt_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaActionPerformed

    private void txt_estanteriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_estanteriaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estanteriaFocusGained

    private void txt_estanteriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_estanteriaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estanteriaFocusLost

    private void txt_estanteriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_estanteriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estanteriaMousePressed

    private void txt_estanteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estanteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estanteriaActionPerformed

    private void txt_existenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_existenciaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaFocusGained

    private void txt_existenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_existenciaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaFocusLost

    private void txt_existenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_existenciaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaMousePressed

    private void txt_existenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_existenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaActionPerformed

    private void btn_Guardar_AceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_AceptarMousePressed
        // TODO add your handling code here:
        btn_Guardar_Aceptar.setBackground(color_naranja);
        btn_Guardar_Aceptar.requestFocus();
    }//GEN-LAST:event_btn_Guardar_AceptarMousePressed

    private void btn_Guardar_AceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_AceptarMouseReleased
        // TODO add your handling code here:
        btn_Guardar_Aceptar.setBackground(color_rojo);
    }//GEN-LAST:event_btn_Guardar_AceptarMouseReleased

    private void btn_Guardar_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_AceptarMouseClicked
    try {
            if(nuevo && cmb_sucursal.getSelectedIndex()>0){
                String est=txt_estanteria.getText(), fil=txt_fila.getText(), 
                        col=txt_columna.getText(), uni=(cmb_unidad.getSelectedIndex()+1)+"";
                if(Integer.parseInt(uni)== cmb_unidad.getItemCount())
                {
                    uni=null;
                }
                conexion.insertarProducto(txt_codigo.getText(),txt_codigoBarra.getText(),
                    txa_descripcion.getText(),Double.parseDouble(ftx_venta.getValue().toString()),
                    Double.parseDouble(ftx_costo.getValue().toString()),est,col,fil,txt_marca.getText(),
                    uni,Integer.parseInt(sucursales_unidades[0].get(cmb_sucursal.getSelectedIndex()-1).toString()),
                    Double.parseDouble(txt_existencia.getText()));
                llenarListado();
                tbl_productosMouseClicked(evt);
//                btn_verMouseClicked(evt); 
                }
            if(modificar){
                String est=txt_estanteria.getText(), fil=txt_fila.getText(), 
                        col=txt_columna.getText();
                conexion.modificarProducto(Integer.parseInt(productoActual.get(0).toString()),txt_codigo.getText(),txt_codigoBarra.getText(),
                    txa_descripcion.getText(),Double.parseDouble(ftx_venta.getValue().toString()),
                    Double.parseDouble(ftx_costo.getValue().toString()),est,col,fil,txt_marca.getText());
                 cargarProducto(Integer.parseInt(productoActual.get(0).toString()));
//                 btn_verMouseClicked(evt);
                    tbl_productosMouseClicked(evt);
                 llenarListado();
            }
        } catch (SQLException|NoSePuedeConectar ex) {
                Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_Guardar_AceptarMouseClicked

    private void txt_codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoFocusGained

    private void txt_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoFocusLost

    private void txt_codigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_codigoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoMousePressed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void lbl_codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_codigoMouseClicked
        // TODO add your handling code here:
        if(nuevo||modificar)
            txt_codigo.requestFocus();
    }//GEN-LAST:event_lbl_codigoMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        if(nuevo||modificar)
            txt_fila.requestFocus();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void cmb_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_unidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_unidadActionPerformed

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        if(btn_eliminar.isEnabled()){
            if(productoActual.size()>0)
             {
                 btn_eliminar.setBackground(color_set);
                 try {
                     DialogoOpcion dialogo= new DialogoOpcion(null,true, DialogoOpcion.ICONO_INTERROGANTE,"Eliminar Producto", "¿Seguro de eliminar este producto?");
                     dialogo.setVisible(true);
                     if(dialogo.isAceptar())
                     {
                         if(conexion.obtenerExistencia(0,Integer.parseInt(productoActual.get(0).toString()))==0)
                             conexion.deshabilitarProducto(Integer.parseInt(productoActual.get(0).toString()));
                         else{
                             dialogo=new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR,"Error","Aún hay existencias del producto");
                             dialogo.setVisible(true);
                         }
                     }
                 } catch (SQLException|NoSePuedeConectar ex) {
                     Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 btn_eliminar.setBackground(color_reset);
                 llenarListado();
                 productoActual=new ArrayList();
                 modoSinDatos();
             }
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseClicked
        if(btn_nuevo.isEnabled()){
//            pnContenido1.setVisible(false);
            pnContenido.setVisible(true);
            btn_modificar.setBackground(color_reset);
            btn_nuevo.setBackground(color_set);
            btn_Cancelar.setVisible(true);
            btn_Guardar_Aceptar.setEnabled(true);
//            btn_ver.setBackground(color_reset);
            modificar=false;
            nuevo=true;
            modoSinDatos();
            cambiarModo();
            txt_codigo.requestFocus();
        }
    }//GEN-LAST:event_btn_nuevoMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        if(btn_modificar.isEnabled()){
            if(productoActual.size()>0)
            {
                btn_Cancelar.setVisible(true);
                btn_Guardar_Aceptar.setEnabled(true);
                btn_modificar.setBackground(color_set);
                btn_nuevo.setBackground(color_reset);
//                btn_ver.setBackground(color_reset);
                modificar=true;
                nuevo=false;
                cambiarModo();
                txt_codigo.requestFocus();
                cargarProductoActual();
            }
        }
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Salir1MouseClicked

    private void tbl_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productosMouseClicked
        // TODO add your handling code here:
       int fila= tbl_productos.getSelectedRow();
       if(fila>-1)
       {
           cargarProducto(tbl_productos.getValueAt(fila,0).toString(),tbl_productos.getValueAt(fila,1).toString(),tbl_productos.getValueAt(fila,2).toString());
       }
    }//GEN-LAST:event_tbl_productosMouseClicked

    private void rbtn_CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_CreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_CreditoActionPerformed

    private void rbtn_Credito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Credito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Credito2ActionPerformed

    private void txt_codigo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo1FocusGained

    private void txt_codigo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigo1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo1FocusLost

    private void txt_codigo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_codigo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo1MousePressed

    private void txt_codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo1ActionPerformed

    private void lbl_codigo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_codigo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_codigo1MouseClicked

    private void rbtn_CreditoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn_CreditoStateChanged
        // TODO add your handling code here:
        llenarListado();
    }//GEN-LAST:event_rbtn_CreditoStateChanged

    private void rbtn_Credito1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn_Credito1StateChanged
        // TODO add your handling code here:
        llenarListado();
    }//GEN-LAST:event_rbtn_Credito1StateChanged

    private void rbtn_Credito2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn_Credito2StateChanged
        // TODO add your handling code here:
        llenarListado();
    }//GEN-LAST:event_rbtn_Credito2StateChanged

    private void cmb_sucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_sucursalActionPerformed

    private void ftx_costoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_costoFocusLost
        // TODO add your handling code here:
        String cadena=ftx_costo.getText();
        if(cadena.matches(("[+-]?\\d*(\\.\\d+)?")))
        ftx_costo.setText("Q"+String.format("%.2f",Double.parseDouble(ftx_costo.getText())));
        else
        ftx_costo.setText("Q"+ftx_costo.getValue().toString());
    }//GEN-LAST:event_ftx_costoFocusLost

    private void ftx_ventaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_ventaFocusLost
        // TODO add your handling code here:
        String cadena=ftx_venta.getText();
        if(cadena.matches(("[+-]?\\d*(\\.\\d+)?")))
        ftx_venta.setText("Q"+String.format("%.2f",Double.parseDouble(ftx_venta.getText())));
        else
        ftx_venta.setText("Q"+ftx_venta.getValue().toString());
    }//GEN-LAST:event_ftx_ventaFocusLost

    private void ftx_ventaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_ventaFocusGained
        // TODO add your handling code here:
        ftx_venta.setText(ftx_venta.getValue().toString());
    }//GEN-LAST:event_ftx_ventaFocusGained

    private void ftx_costoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftx_costoFocusGained
        // TODO add your handling code here:
        ftx_costo.setText(ftx_costo.getValue().toString());
    }//GEN-LAST:event_ftx_costoFocusGained

    private void btn_CancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancelarMouseReleased

    private void btn_CancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancelarMousePressed

    private void btn_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMouseClicked
        modoSinDatos();
        btn_Guardar_Aceptar.setVisible(false);
        btn_Cancelar.setVisible(false);
        cargarProductoActual();
        
    }//GEN-LAST:event_btn_CancelarMouseClicked

    private void btn_Guardar_Aceptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar1MouseClicked

    private void btn_Guardar_Aceptar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar1MousePressed

    private void btn_Guardar_Aceptar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar1MouseReleased

    private void btn_Guardar_Aceptar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar2MouseClicked

    private void btn_Guardar_Aceptar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar2MousePressed

    private void btn_Guardar_Aceptar2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar2MouseReleased

    private void btn_Guardar_Aceptar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar3MouseClicked
        // TODO add your handling code here:
        DialogoOpcion nombre = new DialogoOpcion(null, true, DialogoOpcion.ICONO_INTERROGANTE_DESCRIPCION, "Propiedad", "Inrese Propiedad");
        nombre.setLocationRelativeTo(null);
        nombre.setVisible(true);
        System.out.println(nombre.isAceptar());
        if(nombre.isAceptar()){
            DefaultTableModel modeloProp = (DefaultTableModel) jTable1.getModel();
            modeloProp.addRow(new Object[]{nombre.getComent(),""});
            proxy.addCaracteristica(nombre.getComent());
        }
    }//GEN-LAST:event_btn_Guardar_Aceptar3MouseClicked

    private void btn_Guardar_Aceptar3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar3MousePressed

    private void btn_Guardar_Aceptar3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar3MouseReleased

    private void btn_Guardar_Aceptar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_Guardar_Aceptar4MouseClicked

    private void btn_Guardar_Aceptar4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar4MousePressed

    private void btn_Guardar_Aceptar4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Guardar_Aceptar4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Guardar_Aceptar4MouseReleased
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salir1;
    private javax.swing.JLabel btn_Cancelar;
    private javax.swing.JLabel btn_Guardar_Aceptar;
    private javax.swing.JLabel btn_Guardar_Aceptar1;
    private javax.swing.JLabel btn_Guardar_Aceptar2;
    private javax.swing.JLabel btn_Guardar_Aceptar3;
    private javax.swing.JLabel btn_Guardar_Aceptar4;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel btn_modificar;
    private javax.swing.JLabel btn_nuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_sucursal;
    private javax.swing.JComboBox<String> cmb_unidad;
    private javax.swing.JFormattedTextField ftx_costo;
    private javax.swing.JFormattedTextField ftx_venta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_codigo1;
    private javax.swing.JLabel lbl_codigoBarra;
    private javax.swing.JLabel lbl_precioVenta;
    public static javax.swing.JPanel pnContenido;
    public static javax.swing.JPanel pnDetalle;
    private javax.swing.JPanel pn_herramientas;
    private javax.swing.JRadioButton rbtn_Credito;
    private javax.swing.JRadioButton rbtn_Credito1;
    private javax.swing.JRadioButton rbtn_Credito2;
    private javax.swing.JScrollPane scp_descripcion;
    public static javax.swing.JScrollPane scp_listado;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JTextArea txa_descripcion;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigo1;
    private javax.swing.JTextField txt_codigoBarra;
    private javax.swing.JTextField txt_columna;
    private javax.swing.JTextField txt_estanteria;
    private javax.swing.JTextField txt_existencia;
    private javax.swing.JTextField txt_fila;
    private javax.swing.JTextField txt_marca;
    // End of variables declaration//GEN-END:variables
}
