/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interaz;

import Excepciones.NoSePuedeConectar;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import clases.Base;

/**
 *
 * 
 */
public class Pago extends javax.swing.JDialog {
    
    private Base Conexion_DB; private boolean Seleccionado; private float TotalFac; private int Trabajador_id;
    private float credito, efectivo, cheque1, cheque2, cheque3, otros;
    private String desCheque1, desCheque2, desCheque3, desOtros;
    public Pago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public String getDesCheque1() {
        return desCheque1;
    }

    public String getDesCheque2() {
        return desCheque2;
    }

    public String getDesCheque3() {
        return desCheque3;
    }

    public String getDesOtros() {
        return desOtros;
    }

    public Pago(java.awt.Frame parent, boolean modal, Base Conexion_DB, float Total, boolean Credito, int trabajador_id) {
        super(parent, modal);
        initComponents();
        this.Conexion_DB = Conexion_DB;
        this.TotalFac = Total;
        this.Trabajador_id = trabajador_id;
        Seleccionado = false;
        if (Credito) {
            txt_CreditoDias.setEditable(true);
            txt_CreditoCant.setEditable(true);
            txt_CreditoCant.setText(Total + "");
            txt_CreditoDias.setText("30");
            
        }else {
            txt_Efectivo.requestFocus();
            txt_CreditoDias.setEditable(false);
            txt_CreditoCant.setEnabled(false);
            txt_CreditoDias.setEnabled(false);
            txt_CreditoCant.setEditable(false);
            txt_CreditoCant.setValue(0);
            txt_CreditoDias.setValue(0);
        }
        Saldo();
    }
    private void Saldo(){
        float Total = 0;
        Total += Float.parseFloat(txt_CreditoCant.getText());
        Total += Float.parseFloat(txt_Efectivo.getText());
        Total += Float.parseFloat(txt_Cheque1cant.getText());
        Total += Float.parseFloat(txt_Cheque2cant.getText()); 
        Total += Float.parseFloat(txt_Cheque3cant.getText());
        Total += Float.parseFloat(txt_OtrosCant.getText());
        txt_Total.setValue(Total);
        txt_Saldo.setValue(TotalFac - Total);
        btn_Aceptar2.setEnabled((TotalFac - Total) == 0);
   }

    public float getCredito() {
        return credito;
    }

    public float getEfectivo() {
        return efectivo;
    }

    public float getCheque1() {
        return cheque1;
    }

    public float getCheque2() {
        return cheque2;
    }

    public float getCheque3() {
        return cheque3;
    }

    public float getOtros() {
        return otros;
    }
    
    public boolean isSeleccionado() {
        return Seleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_Nombre9 = new javax.swing.JLabel();
        sep_Nombre7 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_Nombre12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sep_Nombre8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbl_Nombre10 = new javax.swing.JLabel();
        sep_Nombre9 = new javax.swing.JSeparator();
        lbl_Nombre11 = new javax.swing.JLabel();
        sep_Nombre10 = new javax.swing.JSeparator();
        sep_Nombre11 = new javax.swing.JSeparator();
        txt_Cheque1Coment = new javax.swing.JTextField();
        sep_Nombre12 = new javax.swing.JSeparator();
        lbl_Nombre13 = new javax.swing.JLabel();
        sep_Nombre13 = new javax.swing.JSeparator();
        txt_Cheque2Coment = new javax.swing.JTextField();
        sep_Nombre14 = new javax.swing.JSeparator();
        lbl_Nombre14 = new javax.swing.JLabel();
        sep_Nombre15 = new javax.swing.JSeparator();
        txt_Cheque3Coment = new javax.swing.JTextField();
        sep_Nombre16 = new javax.swing.JSeparator();
        txt_OtroComent = new javax.swing.JTextField();
        sep_Nombre17 = new javax.swing.JSeparator();
        lbl_Nombre15 = new javax.swing.JLabel();
        lbl_Nombre16 = new javax.swing.JLabel();
        sep_Nombre18 = new javax.swing.JSeparator();
        lbl_Nombre17 = new javax.swing.JLabel();
        sep_Nombre19 = new javax.swing.JSeparator();
        btn_Cancelar = new javax.swing.JLabel();
        btn_Aceptar2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_Saldo = new javax.swing.JFormattedTextField();
        txt_CreditoDias = new javax.swing.JFormattedTextField();
        txt_Efectivo = new javax.swing.JFormattedTextField();
        txt_Cheque1cant = new javax.swing.JFormattedTextField();
        txt_Cheque2cant = new javax.swing.JFormattedTextField();
        txt_Cheque3cant = new javax.swing.JFormattedTextField();
        txt_OtrosCant = new javax.swing.JFormattedTextField();
        txt_Total = new javax.swing.JFormattedTextField();
        txt_CreditoCant = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Nombre9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lbl_Nombre9.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre9.setText("Crédito:");
        jPanel2.add(lbl_Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 40));

        sep_Nombre7.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre7.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 10));

        jPanel3.setBackground(new java.awt.Color(96, 96, 96));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Titulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Titulo.setText("MÉTODO DE PAGO");
        jPanel3.add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -7, -1, 50));

        lbl_Nombre12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl_Nombre12.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre12.setText("F1 PAGO TOTAL EN EFECTIVO");
        jPanel3.add(lbl_Nombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 180, 40));

        jPanel1.setBackground(new java.awt.Color(128, 128, 128));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 200, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        sep_Nombre8.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre8.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 50, 10));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 64, 64));
        jLabel2.setText("días");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, 60));

        lbl_Nombre10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lbl_Nombre10.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre10.setText("Efectivo:");
        jPanel2.add(lbl_Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 40));

        sep_Nombre9.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre9.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, 10));

        lbl_Nombre11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lbl_Nombre11.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre11.setText("Cheque:");
        jPanel2.add(lbl_Nombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 40));

        sep_Nombre10.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre10.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, 10));

        sep_Nombre11.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre11.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 10));

        txt_Cheque1Coment.setBackground(new java.awt.Color(240, 240, 240));
        txt_Cheque1Coment.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Cheque1Coment.setForeground(new java.awt.Color(64, 64, 64));
        txt_Cheque1Coment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Cheque1Coment.setText("Información del cheque");
        txt_Cheque1Coment.setBorder(null);
        txt_Cheque1Coment.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Cheque1Coment.setSelectedTextColor(new java.awt.Color(68, 68, 68));
        txt_Cheque1Coment.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_Cheque1Coment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Cheque1ComentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Cheque1ComentFocusLost(evt);
            }
        });
        txt_Cheque1Coment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_Cheque1ComentMousePressed(evt);
            }
        });
        txt_Cheque1Coment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cheque1ComentActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Cheque1Coment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 220, 30));

        sep_Nombre12.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre12.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, 10));

        lbl_Nombre13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lbl_Nombre13.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre13.setText("Cheque:");
        jPanel2.add(lbl_Nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 40));

        sep_Nombre13.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre13.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 10));

        txt_Cheque2Coment.setBackground(new java.awt.Color(240, 240, 240));
        txt_Cheque2Coment.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Cheque2Coment.setForeground(new java.awt.Color(64, 64, 64));
        txt_Cheque2Coment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Cheque2Coment.setText("Información del cheque");
        txt_Cheque2Coment.setBorder(null);
        txt_Cheque2Coment.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Cheque2Coment.setSelectedTextColor(new java.awt.Color(68, 68, 68));
        txt_Cheque2Coment.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_Cheque2Coment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Cheque2ComentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Cheque2ComentFocusLost(evt);
            }
        });
        txt_Cheque2Coment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_Cheque2ComentMousePressed(evt);
            }
        });
        txt_Cheque2Coment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cheque2ComentActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Cheque2Coment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 220, 30));

        sep_Nombre14.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre14.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 220, 10));

        lbl_Nombre14.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lbl_Nombre14.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre14.setText("Cheque:");
        jPanel2.add(lbl_Nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 40));

        sep_Nombre15.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre15.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 100, 10));

        txt_Cheque3Coment.setBackground(new java.awt.Color(240, 240, 240));
        txt_Cheque3Coment.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Cheque3Coment.setForeground(new java.awt.Color(64, 64, 64));
        txt_Cheque3Coment.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_Cheque3Coment.setText("Información del cheque");
        txt_Cheque3Coment.setBorder(null);
        txt_Cheque3Coment.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Cheque3Coment.setSelectedTextColor(new java.awt.Color(68, 68, 68));
        txt_Cheque3Coment.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_Cheque3Coment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Cheque3ComentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Cheque3ComentFocusLost(evt);
            }
        });
        txt_Cheque3Coment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_Cheque3ComentMousePressed(evt);
            }
        });
        txt_Cheque3Coment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cheque3ComentActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Cheque3Coment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 220, 30));

        sep_Nombre16.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre16.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 220, 10));

        txt_OtroComent.setBackground(new java.awt.Color(240, 240, 240));
        txt_OtroComent.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_OtroComent.setForeground(new java.awt.Color(64, 64, 64));
        txt_OtroComent.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_OtroComent.setText("Especifique");
        txt_OtroComent.setBorder(null);
        txt_OtroComent.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_OtroComent.setSelectedTextColor(new java.awt.Color(68, 68, 68));
        txt_OtroComent.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_OtroComent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_OtroComentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_OtroComentFocusLost(evt);
            }
        });
        txt_OtroComent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_OtroComentMousePressed(evt);
            }
        });
        txt_OtroComent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_OtroComentActionPerformed(evt);
            }
        });
        jPanel2.add(txt_OtroComent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 220, 30));

        sep_Nombre17.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre17.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 220, 10));

        lbl_Nombre15.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lbl_Nombre15.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre15.setText("Otros:");
        jPanel2.add(lbl_Nombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 40));

        lbl_Nombre16.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lbl_Nombre16.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre16.setText("Total:");
        jPanel2.add(lbl_Nombre16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 40));

        sep_Nombre18.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre18.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 100, 10));

        lbl_Nombre17.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lbl_Nombre17.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre17.setText("Saldo:");
        jPanel2.add(lbl_Nombre17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, 40));

        sep_Nombre19.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre19.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(sep_Nombre19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 150, 10));

        btn_Cancelar.setBackground(new java.awt.Color(255, 51, 51));
        btn_Cancelar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setOpaque(true);
        btn_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelarMouseClicked(evt);
            }
        });
        jPanel2.add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 125, 35));

        btn_Aceptar2.setBackground(new java.awt.Color(255, 51, 51));
        btn_Aceptar2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Aceptar2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Aceptar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Aceptar2.setText("Aceptar");
        btn_Aceptar2.setEnabled(false);
        btn_Aceptar2.setOpaque(true);
        btn_Aceptar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Aceptar2MouseClicked(evt);
            }
        });
        jPanel2.add(btn_Aceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 125, 35));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(64, 64, 64));
        jLabel8.setText("Contraseña:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, -1));

        jPasswordField1.setBackground(new java.awt.Color(240, 240, 240));
        jPasswordField1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.setCaretColor(new java.awt.Color(64, 64, 64));
        jPasswordField1.setSelectedTextColor(new java.awt.Color(68, 68, 68));
        jPasswordField1.setSelectionColor(new java.awt.Color(192, 192, 192));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 280, 30));

        jSeparator5.setBackground(new java.awt.Color(64, 64, 64));
        jSeparator5.setForeground(new java.awt.Color(64, 64, 64));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 280, 6));

        txt_Saldo.setEditable(false);
        txt_Saldo.setBorder(null);
        txt_Saldo.setForeground(new java.awt.Color(255, 51, 51));
        txt_Saldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_Saldo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_Saldo.setText("0.00");
        txt_Saldo.setCaretColor(new java.awt.Color(255, 51, 51));
        txt_Saldo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txt_Saldo.setSelectedTextColor(new java.awt.Color(68, 68, 68));
        txt_Saldo.setSelectionColor(new java.awt.Color(192, 192, 192));
        jPanel2.add(txt_Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 291, 150, -1));

        txt_CreditoDias.setEditable(false);
        txt_CreditoDias.setBorder(null);
        txt_CreditoDias.setForeground(new java.awt.Color(64, 64, 64));
        txt_CreditoDias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_CreditoDias.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_CreditoDias.setText("0");
        txt_CreditoDias.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_CreditoDias.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txt_CreditoDias.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_CreditoDias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CreditoDiasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CreditoDiasFocusLost(evt);
            }
        });
        jPanel2.add(txt_CreditoDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 51, 50, 20));

        txt_Efectivo.setBackground(new java.awt.Color(240, 240, 240));
        txt_Efectivo.setBorder(null);
        txt_Efectivo.setForeground(new java.awt.Color(64, 64, 64));
        txt_Efectivo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_Efectivo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_Efectivo.setText("0.00");
        txt_Efectivo.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Efectivo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Efectivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_EfectivoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_EfectivoFocusLost(evt);
            }
        });
        jPanel2.add(txt_Efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 91, 100, 20));

        txt_Cheque1cant.setBackground(new java.awt.Color(240, 240, 240));
        txt_Cheque1cant.setBorder(null);
        txt_Cheque1cant.setForeground(new java.awt.Color(64, 64, 64));
        txt_Cheque1cant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_Cheque1cant.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_Cheque1cant.setText("0.00");
        txt_Cheque1cant.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Cheque1cant.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Cheque1cant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Cheque1cantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Cheque1cantFocusLost(evt);
            }
        });
        jPanel2.add(txt_Cheque1cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 131, 100, 20));

        txt_Cheque2cant.setBackground(new java.awt.Color(240, 240, 240));
        txt_Cheque2cant.setBorder(null);
        txt_Cheque2cant.setForeground(new java.awt.Color(64, 64, 64));
        txt_Cheque2cant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_Cheque2cant.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_Cheque2cant.setText("0.00");
        txt_Cheque2cant.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Cheque2cant.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Cheque2cant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Cheque2cantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Cheque2cantFocusLost(evt);
            }
        });
        jPanel2.add(txt_Cheque2cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 171, 100, 20));

        txt_Cheque3cant.setBackground(new java.awt.Color(240, 240, 240));
        txt_Cheque3cant.setBorder(null);
        txt_Cheque3cant.setForeground(new java.awt.Color(64, 64, 64));
        txt_Cheque3cant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_Cheque3cant.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_Cheque3cant.setText("0.00");
        txt_Cheque3cant.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Cheque3cant.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Cheque3cant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Cheque3cantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Cheque3cantFocusLost(evt);
            }
        });
        jPanel2.add(txt_Cheque3cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 211, 100, 20));

        txt_OtrosCant.setBackground(new java.awt.Color(240, 240, 240));
        txt_OtrosCant.setBorder(null);
        txt_OtrosCant.setForeground(new java.awt.Color(64, 64, 64));
        txt_OtrosCant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_OtrosCant.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_OtrosCant.setText("0.00");
        txt_OtrosCant.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_OtrosCant.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_OtrosCant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_OtrosCantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_OtrosCantFocusLost(evt);
            }
        });
        jPanel2.add(txt_OtrosCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 251, 100, 20));

        txt_Total.setEditable(false);
        txt_Total.setBorder(null);
        txt_Total.setForeground(new java.awt.Color(64, 64, 64));
        txt_Total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_Total.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_Total.setText("0.00");
        txt_Total.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Total.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jPanel2.add(txt_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 291, 100, -1));

        txt_CreditoCant.setEditable(false);
        txt_CreditoCant.setBorder(null);
        txt_CreditoCant.setForeground(new java.awt.Color(64, 64, 64));
        txt_CreditoCant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_CreditoCant.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt_CreditoCant.setText("0.00");
        txt_CreditoCant.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_CreditoCant.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txt_CreditoCant.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_CreditoCant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CreditoCantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CreditoCantFocusLost(evt);
            }
        });
        jPanel2.add(txt_CreditoCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btn_CancelarMouseClicked

    private void txt_Cheque1ComentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque1ComentFocusGained
        if (txt_Cheque1Coment.getText().equals("INGRESE INFROMACION DEL CHEQUE")) txt_Cheque1Coment.setText("");
    }//GEN-LAST:event_txt_Cheque1ComentFocusGained

    private void txt_Cheque1ComentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque1ComentFocusLost
         if (txt_Cheque1Coment.getText().equals("")) txt_Cheque1Coment.setText("INGRESE INFROMACION DEL CHEQUE");
    }//GEN-LAST:event_txt_Cheque1ComentFocusLost

    private void txt_Cheque1ComentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Cheque1ComentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cheque1ComentMousePressed

    private void txt_Cheque1ComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cheque1ComentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cheque1ComentActionPerformed

    private void txt_Cheque2ComentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque2ComentFocusGained
         if (txt_Cheque2Coment.getText().equals("INGRESE INFROMACION DEL CHEQUE")) txt_Cheque2Coment.setText("");
    }//GEN-LAST:event_txt_Cheque2ComentFocusGained

    private void txt_Cheque2ComentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque2ComentFocusLost
        if (txt_Cheque2Coment.getText().equals("")) txt_Cheque2Coment.setText("INGRESE INFROMACION DEL CHEQUE");
    }//GEN-LAST:event_txt_Cheque2ComentFocusLost

    private void txt_Cheque2ComentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Cheque2ComentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cheque2ComentMousePressed

    private void txt_Cheque2ComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cheque2ComentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cheque2ComentActionPerformed

    private void txt_Cheque3ComentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque3ComentFocusGained
         if (txt_Cheque3Coment.getText().equals("INGRESE INFROMACION DEL CHEQUE")) txt_Cheque3Coment.setText("");
    }//GEN-LAST:event_txt_Cheque3ComentFocusGained

    private void txt_Cheque3ComentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque3ComentFocusLost
        if (txt_Cheque3Coment.getText().equals("")) txt_Cheque3Coment.setText("INGRESE INFROMACION DEL CHEQUE");
    }//GEN-LAST:event_txt_Cheque3ComentFocusLost

    private void txt_Cheque3ComentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Cheque3ComentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cheque3ComentMousePressed

    private void txt_Cheque3ComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cheque3ComentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cheque3ComentActionPerformed

    private void txt_OtroComentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_OtroComentFocusGained
        if (txt_OtroComent.getText().equals("ESPECIFIQUE")) txt_OtroComent.setText("");
    }//GEN-LAST:event_txt_OtroComentFocusGained

    private void txt_OtroComentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_OtroComentFocusLost
        if (txt_OtroComent.getText().equals("")) txt_OtroComent.setText("ESPECIFIQUE");
    }//GEN-LAST:event_txt_OtroComentFocusLost

    private void txt_OtroComentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_OtroComentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OtroComentMousePressed

    private void txt_OtroComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_OtroComentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OtroComentActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        int code = evt.getKeyCode();
        if(code==KeyEvent.VK_ENTER){
           okey();
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased
    
    private void okey(){
         try {
             Saldo();
             if (txt_Saldo.getText().equals("0.00")) {
                if (Conexion_DB.login(Conexion_DB.obtenerUsuario(Trabajador_id), new String(jPasswordField1.getPassword())) == 1) {
                    credito = new Float(txt_CreditoCant.getText());
                    efectivo = new Float(txt_Efectivo.getText());
                    cheque2 = new Float(txt_Cheque2cant.getText());
                    cheque3 = new Float(txt_Cheque3cant.getText());
                    cheque1 = new Float(txt_Cheque1cant.getText());
                    otros = new Float(txt_OtrosCant.getText());
                    desCheque1 = (txt_Cheque1Coment.getText().equals("INGRESE INFROMACION DEL CHEQUE"))? "": txt_Cheque1Coment.getText();
                    desCheque2 = (txt_Cheque2Coment.getText().equals("INGRESE INFROMACION DEL CHEQUE"))? "": txt_Cheque2Coment.getText();
                    desCheque3 = (txt_Cheque3Coment.getText().equals("INGRESE INFROMACION DEL CHEQUE"))? "": txt_Cheque3Coment.getText();
                    desOtros = (txt_OtroComent.getText().equals("INGRESE INFROMACION DEL CHEQUE"))? "": txt_OtroComent.getText();
                    Seleccionado = true;
                    this.setVisible(false);
                }else{
                    DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "ERROR", "CLAVE INCORRECTA");
                    dialogo.setVisible(true);
                    Seleccionado = false;
                }
             }else{
                    DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "ERROR", "EL SALDO DEBE SER IGUAL A 0"
                            + " \nLA SUMA DE LOS METODOS DE PAGO DEBER SER IGUAL AL TOTAL DE LA FACTURA");
                    dialogo.setVisible(true);
                    Seleccionado = false;
             }
            } catch (NoSePuedeConectar | SQLException ex) {
                DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "ERROR", ex.getMessage());
                dialogo.setVisible(true);
            }
    }
    private void txt_CreditoCantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CreditoCantFocusGained
        if (txt_CreditoCant.getText().equals("0.00")) txt_CreditoCant.setText("");
        
    }//GEN-LAST:event_txt_CreditoCantFocusGained

    private void txt_CreditoCantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CreditoCantFocusLost
        if (txt_CreditoCant.getText().equals("")) txt_CreditoCant.setText("0.00");
        Saldo();
    }//GEN-LAST:event_txt_CreditoCantFocusLost

    private void txt_EfectivoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EfectivoFocusGained
        if (txt_Efectivo.getText().equals("0.00")) txt_Efectivo.setText("");
    }//GEN-LAST:event_txt_EfectivoFocusGained

    private void txt_Cheque1cantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque1cantFocusGained
        if (txt_Cheque1cant.getText().equals("0.00")) txt_Cheque1cant.setText("");
    }//GEN-LAST:event_txt_Cheque1cantFocusGained

    private void txt_Cheque2cantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque2cantFocusGained
        if (txt_Cheque2cant.getText().equals("0.00")) txt_Cheque2cant.setText("");
    }//GEN-LAST:event_txt_Cheque2cantFocusGained

    private void txt_Cheque3cantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque3cantFocusGained
        if (txt_Cheque3cant.getText().equals("0.00")) txt_Cheque3cant.setText("");
    }//GEN-LAST:event_txt_Cheque3cantFocusGained

    private void txt_OtrosCantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_OtrosCantFocusGained
        if (txt_OtrosCant.getText().equals("0.00")) txt_OtrosCant.setText("");
    }//GEN-LAST:event_txt_OtrosCantFocusGained

    private void txt_EfectivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EfectivoFocusLost
        if (txt_Efectivo.getText().equals("")) txt_Efectivo.setText("0.00");
        Saldo();
    }//GEN-LAST:event_txt_EfectivoFocusLost

    private void txt_Cheque1cantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque1cantFocusLost
        if (txt_Cheque1cant.getText().equals("")) txt_Cheque1cant.setText("0.00");
        Saldo();
    }//GEN-LAST:event_txt_Cheque1cantFocusLost

    private void txt_Cheque2cantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque2cantFocusLost
        if (txt_Cheque2cant.getText().equals("")) txt_Cheque2cant.setText("0.00");
        Saldo();
    }//GEN-LAST:event_txt_Cheque2cantFocusLost

    private void txt_Cheque3cantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cheque3cantFocusLost
        if (txt_Cheque3cant.getText().equals("")) txt_Cheque3cant.setText("0.00");
        Saldo();
    }//GEN-LAST:event_txt_Cheque3cantFocusLost

    private void txt_OtrosCantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_OtrosCantFocusLost
        if (txt_OtrosCant.getText().equals("")) txt_OtrosCant.setText("0.00");
        Saldo();
    }//GEN-LAST:event_txt_OtrosCantFocusLost

    private void txt_CreditoDiasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CreditoDiasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CreditoDiasFocusGained

    private void txt_CreditoDiasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CreditoDiasFocusLost
        if (txt_CreditoDias.getText().startsWith("-")){txt_CreditoDias.setText("0");}
        if (txt_CreditoDias.getText().equals("0")) {
            txt_CreditoCant.setText("0.00");
            txt_CreditoCant.setEnabled(false);
        }else {txt_CreditoCant.setEnabled(true);}
    }//GEN-LAST:event_txt_CreditoDiasFocusLost

    private void btn_Aceptar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Aceptar2MouseClicked
        okey();
    }//GEN-LAST:event_btn_Aceptar2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pago dialog = new Pago(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Aceptar2;
    private javax.swing.JLabel btn_Cancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_Nombre10;
    private javax.swing.JLabel lbl_Nombre11;
    private javax.swing.JLabel lbl_Nombre12;
    private javax.swing.JLabel lbl_Nombre13;
    private javax.swing.JLabel lbl_Nombre14;
    private javax.swing.JLabel lbl_Nombre15;
    private javax.swing.JLabel lbl_Nombre16;
    private javax.swing.JLabel lbl_Nombre17;
    private javax.swing.JLabel lbl_Nombre9;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JSeparator sep_Nombre10;
    private javax.swing.JSeparator sep_Nombre11;
    private javax.swing.JSeparator sep_Nombre12;
    private javax.swing.JSeparator sep_Nombre13;
    private javax.swing.JSeparator sep_Nombre14;
    private javax.swing.JSeparator sep_Nombre15;
    private javax.swing.JSeparator sep_Nombre16;
    private javax.swing.JSeparator sep_Nombre17;
    private javax.swing.JSeparator sep_Nombre18;
    private javax.swing.JSeparator sep_Nombre19;
    private javax.swing.JSeparator sep_Nombre7;
    private javax.swing.JSeparator sep_Nombre8;
    private javax.swing.JSeparator sep_Nombre9;
    private javax.swing.JTextField txt_Cheque1Coment;
    private javax.swing.JFormattedTextField txt_Cheque1cant;
    private javax.swing.JTextField txt_Cheque2Coment;
    private javax.swing.JFormattedTextField txt_Cheque2cant;
    private javax.swing.JTextField txt_Cheque3Coment;
    private javax.swing.JFormattedTextField txt_Cheque3cant;
    private javax.swing.JFormattedTextField txt_CreditoCant;
    private javax.swing.JFormattedTextField txt_CreditoDias;
    private javax.swing.JFormattedTextField txt_Efectivo;
    private javax.swing.JTextField txt_OtroComent;
    private javax.swing.JFormattedTextField txt_OtrosCant;
    private javax.swing.JFormattedTextField txt_Saldo;
    private javax.swing.JFormattedTextField txt_Total;
    // End of variables declaration//GEN-END:variables
}
