/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interaz;

import Excepciones.*;
import clases.Conexion;
import clases.controladorCompras;
import clases.controladorVentas;
import clases.manejoControlador;
import clases.movimientoProductos;
import java.sql.SQLException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 *
 */
public class Pedidos extends javax.swing.JPanel implements movimientoProductos{

    private DefaultTableModel Productos;
    private final Conexion Conexion_DB = new Conexion();
    private final DialogodeMensaje dialogo = new DialogodeMensaje();
    public Pedidos() {
        initComponents();
        try {
            lbl_Orden.setText(Conexion_DB.numeroPedido()+"");
        } catch (SQLException|NoSePuedeConectar ex) {
            dialogo.setContenido("ERROR", ex.getMessage(), DialogodeMensaje.ICONO_ERROR);
            dialogo.setVisible(true);
        }
    }
    private void iniciarTablaProductos() {
//        
        Productos = new DefaultTableModel(null, new String[]{"Código", "Descripción", "Cantidad", "P/Unitario", "P/Total"}){
            boolean[] canEdit = new boolean [] {
        false, false, true, true, false
            };
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
            }
        };
        tabla_detalle.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
               total();
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_detalle = new javax.swing.JTable();
        btn_Nuevo = new javax.swing.JLabel();
        btn_Consultar = new javax.swing.JLabel();
        btn_Editar = new javax.swing.JLabel();
        sep_Nombre = new javax.swing.JSeparator();
        txt_Nombre = new javax.swing.JTextField();
        lbl_Nombre = new javax.swing.JLabel();
        btn_Seleccion = new javax.swing.JLabel();
        lbl_Orden = new javax.swing.JLabel();
        txt_Factura = new javax.swing.JTextField();
        sep_Nombre1 = new javax.swing.JSeparator();
        lbl_Nombre2 = new javax.swing.JLabel();
        lbl_Nombre3 = new javax.swing.JLabel();
        lbl_Deuda = new javax.swing.JLabel();
        txt_Total = new javax.swing.JTextField();
        sep_Deuda = new javax.swing.JSeparator();
        lbl_Deuda1 = new javax.swing.JLabel();
        txt_Abonos = new javax.swing.JTextField();
        sep_Deuda1 = new javax.swing.JSeparator();
        lbl_Deuda2 = new javax.swing.JLabel();
        txt_Saldo = new javax.swing.JTextField();
        sep_Deuda2 = new javax.swing.JSeparator();
        rbtn_Credito = new javax.swing.JRadioButton();
        btn_Seleccion1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_detalle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tabla_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_detalle.setToolTipText("<html>\n<head>\n<style>\n.contenedor{background:#F0F0F0;color:#0A0A0A;margin:0;padding-left:5px;padding-right:5px;font-size:1.1em;font-family:century gothic;font-weight: lighter;}\n</style>\n</head>\n<body>\n<h4 class=\"contenedor\">F1 para agregar un producto</h4>\n</body>\n</html>");
        tabla_detalle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla_detalle.setGridColor(new java.awt.Color(96, 96, 96));
        tabla_detalle.setRowHeight(24);
        tabla_detalle.setSelectionBackground(new java.awt.Color(192, 192, 192));
        tabla_detalle.setSelectionForeground(new java.awt.Color(64, 64, 64));
        tabla_detalle.setShowVerticalLines(false);
        tabla_detalle.getTableHeader().setReorderingAllowed(false);
        tabla_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_detalleMousePressed(evt);
            }
        });
        tabla_detalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_detalleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_detalleKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_detalle);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 349, 860, 250));

        btn_Nuevo.setBackground(new java.awt.Color(255, 51, 51));
        btn_Nuevo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Nuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.setOpaque(true);
        btn_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NuevoMouseClicked(evt);
            }
        });
        add(btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 125, 35));

        btn_Consultar.setBackground(new java.awt.Color(255, 51, 51));
        btn_Consultar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Consultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Consultar.setText("Consultar");
        btn_Consultar.setOpaque(true);
        btn_Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ConsultarMouseClicked(evt);
            }
        });
        add(btn_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 125, 35));

        btn_Editar.setBackground(new java.awt.Color(255, 51, 51));
        btn_Editar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_Editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Editar.setText("Editar");
        btn_Editar.setOpaque(true);
        btn_Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditarMouseClicked(evt);
            }
        });
        add(btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 125, 35));

        sep_Nombre.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre.setForeground(new java.awt.Color(64, 64, 64));
        add(sep_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 360, 10));

        txt_Nombre.setEditable(false);
        txt_Nombre.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Nombre.setForeground(new java.awt.Color(64, 64, 64));
        txt_Nombre.setText("Nombre del proveedor");
        txt_Nombre.setBorder(null);
        txt_Nombre.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Nombre.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_Nombre.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NombreFocusLost(evt);
            }
        });
        txt_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_NombreMousePressed(evt);
            }
        });
        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 360, 26));

        lbl_Nombre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre.setText("Proveedor");
        add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        btn_Seleccion.setBackground(new java.awt.Color(255, 51, 51));
        btn_Seleccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Seleccion.setForeground(new java.awt.Color(240, 240, 240));
        btn_Seleccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Seleccion.setText("Seleccionar");
        btn_Seleccion.setOpaque(true);
        btn_Seleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SeleccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SeleccionMouseEntered(evt);
            }
        });
        add(btn_Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, 20));

        lbl_Orden.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lbl_Orden.setForeground(new java.awt.Color(255, 51, 51));
        lbl_Orden.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Orden.setText("000001");
        add(lbl_Orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        txt_Factura.setBackground(new java.awt.Color(240, 240, 240));
        txt_Factura.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Factura.setForeground(new java.awt.Color(64, 64, 64));
        txt_Factura.setText("Ingrese número de factura");
        txt_Factura.setBorder(null);
        txt_Factura.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Factura.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_Factura.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_Factura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FacturaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FacturaFocusLost(evt);
            }
        });
        txt_Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_FacturaMousePressed(evt);
            }
        });
        txt_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FacturaActionPerformed(evt);
            }
        });
        add(txt_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 260, 26));

        sep_Nombre1.setBackground(new java.awt.Color(64, 64, 64));
        sep_Nombre1.setForeground(new java.awt.Color(64, 64, 64));
        add(sep_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 260, 10));

        lbl_Nombre2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_Nombre2.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre2.setText("Factura");
        add(lbl_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lbl_Nombre3.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lbl_Nombre3.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Nombre3.setText("Orden No.");
        add(lbl_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        lbl_Deuda.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_Deuda.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Deuda.setText("Total");
        add(lbl_Deuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        txt_Total.setBackground(new java.awt.Color(240, 240, 240));
        txt_Total.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Total.setForeground(new java.awt.Color(64, 64, 64));
        txt_Total.setText("0.00");
        txt_Total.setBorder(null);
        txt_Total.setCaretColor(new java.awt.Color(64, 64, 64));
        txt_Total.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txt_Total.setEnabled(false);
        txt_Total.setSelectedTextColor(new java.awt.Color(64, 64, 64));
        txt_Total.setSelectionColor(new java.awt.Color(192, 192, 192));
        txt_Total.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TotalFocusLost(evt);
            }
        });
        txt_Total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_TotalMousePressed(evt);
            }
        });
        txt_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TotalActionPerformed(evt);
            }
        });
        add(txt_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 210, 26));

        sep_Deuda.setBackground(new java.awt.Color(64, 64, 64));
        sep_Deuda.setForeground(new java.awt.Color(64, 64, 64));
        add(sep_Deuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 220, -1));

        lbl_Deuda1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_Deuda1.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Deuda1.setText("Abonos");
        add(lbl_Deuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        txt_Abonos.setBackground(new java.awt.Color(240, 240, 240));
        txt_Abonos.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Abonos.setForeground(new java.awt.Color(64, 64, 64));
        txt_Abonos.setText("0.00");
        txt_Abonos.setBorder(null);
        txt_Abonos.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Abonos.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txt_Abonos.setEnabled(false);
        txt_Abonos.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Abonos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AbonosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_AbonosFocusLost(evt);
            }
        });
        txt_Abonos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_AbonosMousePressed(evt);
            }
        });
        txt_Abonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AbonosActionPerformed(evt);
            }
        });
        add(txt_Abonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 220, 26));

        sep_Deuda1.setBackground(new java.awt.Color(64, 64, 64));
        sep_Deuda1.setForeground(new java.awt.Color(64, 64, 64));
        add(sep_Deuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 210, 10));

        lbl_Deuda2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_Deuda2.setForeground(new java.awt.Color(64, 64, 64));
        lbl_Deuda2.setText("Saldo");
        add(lbl_Deuda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        txt_Saldo.setBackground(new java.awt.Color(240, 240, 240));
        txt_Saldo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txt_Saldo.setForeground(new java.awt.Color(64, 64, 64));
        txt_Saldo.setText("0.00");
        txt_Saldo.setBorder(null);
        txt_Saldo.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Saldo.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txt_Saldo.setEnabled(false);
        txt_Saldo.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_Saldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_SaldoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_SaldoFocusLost(evt);
            }
        });
        txt_Saldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_SaldoMousePressed(evt);
            }
        });
        txt_Saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SaldoActionPerformed(evt);
            }
        });
        add(txt_Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 220, 26));

        sep_Deuda2.setBackground(new java.awt.Color(64, 64, 64));
        sep_Deuda2.setForeground(new java.awt.Color(64, 64, 64));
        add(sep_Deuda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 220, 10));

        rbtn_Credito.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        rbtn_Credito.setForeground(new java.awt.Color(64, 64, 64));
        rbtn_Credito.setSelected(true);
        rbtn_Credito.setText("Crédito");
        rbtn_Credito.setBorder(null);
        rbtn_Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_CreditoActionPerformed(evt);
            }
        });
        add(rbtn_Credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 400, -1));

        btn_Seleccion1.setBackground(new java.awt.Color(255, 51, 51));
        btn_Seleccion1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Seleccion1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Seleccion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Seleccion1.setText("Pagos");
        btn_Seleccion1.setEnabled(false);
        btn_Seleccion1.setOpaque(true);
        btn_Seleccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Seleccion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Seleccion1MouseEntered(evt);
            }
        });
        add(btn_Seleccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 90, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NuevoMouseClicked
        if (btn_Consultar.getText().equals("Consultar")) {
            iniciarTablaProductos();
            Productos.addRow(new String[]{});
            tabla_detalle.setModel(Productos);
            btn_Seleccion.setEnabled(true);
            btn_Consultar.setText("Guardar");
            btn_Editar.setText("Cancelar");
            try {
            lbl_Orden.setText(Conexion_DB.numeroPedido()+"");
        } catch (SQLException|NoSePuedeConectar ex) {
            dialogo.setContenido("ERROR", ex.getMessage(), DialogodeMensaje.ICONO_ERROR);
            dialogo.setVisible(true);
        }
        }
        
    }//GEN-LAST:event_btn_NuevoMouseClicked

    private void btn_ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConsultarMouseClicked
        if (btn_Consultar.getText().equals("Guardar")) {
            try {
                if (!txt_Nombre.getText().equals("64,64,64") && !txt_Nombre.getText().equals("")) {
                    Conexion_DB.crearPedido(((txt_Factura.getText().equals("Ingrese número de factura")) ? "": txt_Factura.getText()), total, rbtn_Credito.isSelected());
                    dialogo.setContenido("INFORMACIÓN", "Se ha guardado exitosamente", DialogodeMensaje.ICONO_INFORMACION);
                    dialogo.setVisible(true);
                    lbl_Orden.setText(Conexion_DB.numeroPedido()+"");
                    for (int i = 0; i < tabla_detalle.getRowCount() - 1; i++) {
                        Conexion_DB.insertarDetallePedido(Conexion_DB.idCodigo(tabla_detalle.getValueAt(i, 0).toString()), Conexion_DB.idProve(txt_Nombre.getText()), Conexion_DB.numeroPedido(), Float.parseFloat(tabla_detalle.getValueAt(i, 3).toString()), Float.parseFloat(tabla_detalle.getValueAt(i, 2).toString()));
                    }
                }else{
                    dialogo.setContenido("INFORMACIÓN", "Seleccione un proveedor", DialogodeMensaje.ICONO_INFORMACION);
                    dialogo.setVisible(true);
                }
                
            } catch (SQLException|NoSePuedeConectar ex) {
                dialogo.setContenido("ERROR", ex.getMessage(), DialogodeMensaje.ICONO_ERROR);
                dialogo.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_ConsultarMouseClicked

    private void btn_EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EditarMouseClicked

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreMousePressed

    private void txt_NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusLost
        if (txt_Nombre.getText().equals("")) txt_Nombre.setText("Ingrese el nombre del proveedor");
    }//GEN-LAST:event_txt_NombreFocusLost

    private void txt_NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusGained
        if (txt_Nombre.getText().equals("Ingrese el nombre del proveedor")) txt_Nombre.setText("");
    }//GEN-LAST:event_txt_NombreFocusGained

    private void btn_SeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeleccionMouseClicked
        selectorProveedor selector = new selectorProveedor();
        selector.setTxt(txt_Nombre);
        selector.setVisible(true);

    }//GEN-LAST:event_btn_SeleccionMouseClicked

    private void btn_SeleccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeleccionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SeleccionMouseEntered

    private void txt_FacturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FacturaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FacturaFocusGained

    private void txt_FacturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FacturaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FacturaFocusLost

    private void txt_FacturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FacturaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FacturaMousePressed

    private void txt_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FacturaActionPerformed

    private void txt_TotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TotalFocusGained
        // TODO add your handling code here:
        if(txt_Total.getText().equals("Ingrese el nombre de usuario"))txt_Total.setText("");
    }//GEN-LAST:event_txt_TotalFocusGained

    private void txt_TotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TotalFocusLost
        // TODO add your handling code here:
        if(txt_Total.getText().equals("")) txt_Total.setText("Ingrese el nombre de usuario");
    }//GEN-LAST:event_txt_TotalFocusLost

    private void txt_TotalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TotalMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalMousePressed

    private void txt_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalActionPerformed

    private void txt_AbonosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AbonosFocusGained
        // TODO add your handling code here:
        if(txt_Total.getText().equals("Ingrese el nombre de usuario"))txt_Total.setText("");
    }//GEN-LAST:event_txt_AbonosFocusGained

    private void txt_AbonosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AbonosFocusLost
        // TODO add your handling code here:
        if(txt_Total.getText().equals("")) txt_Total.setText("Ingrese el nombre de usuario");
    }//GEN-LAST:event_txt_AbonosFocusLost

    private void txt_AbonosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_AbonosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AbonosMousePressed

    private void txt_AbonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AbonosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AbonosActionPerformed

    private void txt_SaldoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_SaldoFocusGained
        // TODO add your handling code here:
        if(txt_Total.getText().equals("Ingrese el nombre de usuario"))txt_Total.setText("");
    }//GEN-LAST:event_txt_SaldoFocusGained

    private void txt_SaldoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_SaldoFocusLost
        // TODO add your handling code here:
        if(txt_Total.getText().equals("")) txt_Total.setText("Ingrese el nombre de usuario");
    }//GEN-LAST:event_txt_SaldoFocusLost

    private void txt_SaldoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_SaldoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SaldoMousePressed

    private void txt_SaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SaldoActionPerformed

    private void btn_Seleccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Seleccion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Seleccion1MouseClicked

    private void btn_Seleccion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Seleccion1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Seleccion1MouseEntered

    private void tabla_detalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_detalleKeyPressed
       
    }//GEN-LAST:event_tabla_detalleKeyPressed
    private float total = 0;
    private void tabla_detalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_detalleKeyReleased
        if(btn_Consultar.getText().equals("Guardar")){
            if (evt.getKeyCode() == 112) {
                selectorProducto selector = new selectorProducto();
                selector.setProductos(Productos);
                selector.setVisible(true);
            }
            if (evt.getKeyCode() == 114) {
                if (Productos.getRowCount()>1) {
                    Productos.removeRow(tabla_detalle.getSelectedRow());
                    total();
                }

            }
            if (evt.getKeyCode() == 38) {
                int seleccion = tabla_detalle.getSelectedRow() + 1;
                if (tabla_detalle.getRowCount() != seleccion && seleccion != -1){
                    float cantidad = Float.parseFloat(tabla_detalle.getValueAt(seleccion, 2).toString());
                    float precio = Float.parseFloat(tabla_detalle.getValueAt(seleccion, 3).toString());
                    tabla_detalle.setValueAt("" + (cantidad * precio), seleccion, 4);
                    total();
                }
            }
            if (evt.getKeyCode() == 40 || evt.getKeyCode() ==13 || evt.getKeyCode() == 9) {
                int seleccion = tabla_detalle.getSelectedRow() - 1;
                if (tabla_detalle.getRowCount() != seleccion && seleccion != -1){
                    float cantidad = Float.parseFloat(tabla_detalle.getValueAt(seleccion, 2).toString());
                    float precio = Float.parseFloat(tabla_detalle.getValueAt(seleccion, 3).toString());
                    tabla_detalle.setValueAt("" + (cantidad * precio), seleccion, 4);
                    total();
                }
            }
        }
    }//GEN-LAST:event_tabla_detalleKeyReleased
    private void total(){
        int cant = tabla_detalle.getRowCount() - 1;
        total =0;
        for (int i = 0; i < cant; i++) {
            total += Float.parseFloat(tabla_detalle.getValueAt(i, 4).toString());
        }
        txt_Total.setText(total+"");
        txt_Saldo.setText((total - Float.parseFloat(txt_Abonos.getText())) + "");
    }
    private void tabla_detalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_detalleMousePressed
        
    }//GEN-LAST:event_tabla_detalleMousePressed

    private void rbtn_CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_CreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_CreditoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Consultar;
    private javax.swing.JLabel btn_Editar;
    private javax.swing.JLabel btn_Nuevo;
    private javax.swing.JLabel btn_Seleccion;
    private javax.swing.JLabel btn_Seleccion1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Deuda;
    private javax.swing.JLabel lbl_Deuda1;
    private javax.swing.JLabel lbl_Deuda2;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Nombre2;
    private javax.swing.JLabel lbl_Nombre3;
    private javax.swing.JLabel lbl_Orden;
    private javax.swing.JRadioButton rbtn_Credito;
    private javax.swing.JSeparator sep_Deuda;
    private javax.swing.JSeparator sep_Deuda1;
    private javax.swing.JSeparator sep_Deuda2;
    private javax.swing.JSeparator sep_Nombre;
    private javax.swing.JSeparator sep_Nombre1;
    private javax.swing.JTable tabla_detalle;
    private javax.swing.JTextField txt_Abonos;
    private javax.swing.JTextField txt_Factura;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Saldo;
    private javax.swing.JTextField txt_Total;
    // End of variables declaration//GEN-END:variables

    @Override
    public void guardar() {
        manejoControlador fabrica = new controladorCompras();
        fabrica.nuevoDocumento();
    }
}
