/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interaz;

import Excepciones.NoSePuedeConectar;
import Excepciones.NoSePuedeEscribirArchivo;
import clases.*;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFrame;

/**
 *
 * 
 */
public class Seguridad extends javax.swing.JPanel {
    public final static String marcaInicio="SCE";
    public final static String claveCifrado = "Sistema de Control Empresarial";
    private Base conexion;
    Color color_set = new Color(128,128,128);
    Color color_reset = new Color(96,96,96);
    /**
     * Creates new form Seguridad
     */
    public Seguridad(Base conexion) {
        initComponents();  
        this.conexion=conexion;
        //Hacemos invisibles todos lo paneles que no deben mostrarse desde el inicio
        eliminarPanel.setVisible(false);
        ingresarPanel.setVisible(false);
        modificarPanel.setVisible(false);
        conexionPanel.setVisible(false);
        usuariosPanel1.setVisible(false);
        //Ponemos los paneles en el mismo punto, de tal manera que todos estén en el centro, y no regados en el JFrame
        ingresarPanel.setBounds(eliminarPanel.getBounds().x, eliminarPanel.getBounds().y, ingresarPanel.getBounds().width, ingresarPanel.getBounds().height);
        conexionPanel.setBounds(eliminarPanel.getBounds().x, eliminarPanel.getBounds().y,conexionPanel.getBounds().width,conexionPanel.getBounds().height);
        modificarPanel.setBounds(eliminarPanel.getBounds().x, eliminarPanel.getBounds().y,modificarPanel.getBounds().width,modificarPanel.getBounds().height);
        if(conexion.getUsuario().getIdPermisos()>1){
            gesUsuariosButton.setEnabled(false);
            gesConButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conexionPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        ipField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bdField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        cancelarGesButton = new javax.swing.JLabel();
        probarDBButton = new javax.swing.JLabel();
        guardarDBButton = new javax.swing.JLabel();
        eliminarPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        usuariosCombo1 = new javax.swing.JComboBox<>();
        userEButton = new javax.swing.JLabel();
        cancelarElButton = new javax.swing.JLabel();
        ingresarPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        userIField = new javax.swing.JTextField();
        passIField = new javax.swing.JPasswordField();
        passIField2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userIButtton = new javax.swing.JLabel();
        cancelarInButton = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        trabajadoresCombo = new javax.swing.JComboBox<>();
        permisosCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        usuariosPanel1 = new javax.swing.JPanel();
        pn_herramientas2 = new javax.swing.JPanel();
        verUsInButton = new javax.swing.JLabel();
        verUsModButton = new javax.swing.JLabel();
        verUsElButton = new javax.swing.JLabel();
        modificarPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        usuariosMCombo = new javax.swing.JComboBox<>();
        cambiarMButton = new javax.swing.JLabel();
        cancelarMButton = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        permisosMCombo = new javax.swing.JComboBox<>();
        pn_herramientas1 = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        gesUsuariosButton = new javax.swing.JLabel();
        gesConButton = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));
        setPreferredSize(new java.awt.Dimension(940, 650));
        setLayout(null);

        conexionPanel.setBackground(new java.awt.Color(0, 0, 0));
        conexionPanel.setForeground(new java.awt.Color(255, 255, 255));
        conexionPanel.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 64, 64));
        jLabel4.setText("Usuario del SGBD:");

        passField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 64, 64));
        jLabel1.setText("Dirección del servidor:");

        ipField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 64, 64));
        jLabel2.setText("Contraseña:");

        bdField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 64, 64));
        jLabel3.setText("Nombre de la BD:");

        userField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        passField1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(64, 64, 64));
        jLabel9.setText("Confirme contraseña:");

        cancelarGesButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelarGesButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cancelarGesButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarGesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarGesButton.setText("Cancelar");
        cancelarGesButton.setOpaque(true);
        cancelarGesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarGesButtonMouseClicked(evt);
            }
        });

        probarDBButton.setBackground(new java.awt.Color(255, 51, 51));
        probarDBButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        probarDBButton.setForeground(new java.awt.Color(255, 255, 255));
        probarDBButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        probarDBButton.setText("Probar");
        probarDBButton.setOpaque(true);
        probarDBButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                probarDBButtonMouseClicked(evt);
            }
        });

        guardarDBButton.setBackground(new java.awt.Color(255, 51, 51));
        guardarDBButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        guardarDBButton.setForeground(new java.awt.Color(255, 255, 255));
        guardarDBButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarDBButton.setText("Guardar");
        guardarDBButton.setOpaque(true);
        guardarDBButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarDBButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout conexionPanelLayout = new javax.swing.GroupLayout(conexionPanel);
        conexionPanel.setLayout(conexionPanelLayout);
        conexionPanelLayout.setHorizontalGroup(
            conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conexionPanelLayout.createSequentialGroup()
                .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(conexionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(21, 21, 21)
                        .addComponent(passField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, conexionPanelLayout.createSequentialGroup()
                        .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(14, 14, 14)
                        .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userField)
                            .addComponent(bdField)
                            .addComponent(ipField, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(passField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, conexionPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarGesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addGap(15, 15, 15))
            .addGroup(conexionPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(probarDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        conexionPanelLayout.setVerticalGroup(
            conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conexionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(passField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(probarDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(conexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarGesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(conexionPanel);
        conexionPanel.setBounds(510, 230, 400, 280);

        eliminarPanel.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 64, 64));
        jLabel5.setText("Usuario:");

        usuariosCombo1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        userEButton.setBackground(new java.awt.Color(255, 51, 51));
        userEButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        userEButton.setForeground(new java.awt.Color(255, 255, 255));
        userEButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userEButton.setText("Eliminar");
        userEButton.setOpaque(true);
        userEButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userEButtonMouseClicked(evt);
            }
        });

        cancelarElButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelarElButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cancelarElButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarElButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarElButton.setText("Cancelar");
        cancelarElButton.setOpaque(true);
        cancelarElButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarElButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eliminarPanelLayout = new javax.swing.GroupLayout(eliminarPanel);
        eliminarPanel.setLayout(eliminarPanelLayout);
        eliminarPanelLayout.setHorizontalGroup(
            eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarPanelLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarPanelLayout.createSequentialGroup()
                        .addComponent(userEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(cancelarElButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eliminarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usuariosCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );
        eliminarPanelLayout.setVerticalGroup(
            eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usuariosCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarElButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(eliminarPanel);
        eliminarPanel.setBounds(220, 128, 470, 100);

        ingresarPanel.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(64, 64, 64));
        jLabel6.setText("Nombre de Usuario:");

        userIField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        userIField.setNextFocusableComponent(passIField);

        passIField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        passIField.setNextFocusableComponent(passIField2);

        passIField2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        passIField2.setNextFocusableComponent(permisosCombo);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 64, 64));
        jLabel7.setText("Contraseña:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(64, 64, 64));
        jLabel8.setText("Confirmar Contraseña:");

        userIButtton.setBackground(new java.awt.Color(255, 51, 51));
        userIButtton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        userIButtton.setForeground(new java.awt.Color(255, 255, 255));
        userIButtton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIButtton.setText("Ingreso");
        userIButtton.setOpaque(true);
        userIButtton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userIButttonMouseClicked(evt);
            }
        });

        cancelarInButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelarInButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cancelarInButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarInButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarInButton.setText("Cancelar");
        cancelarInButton.setOpaque(true);
        cancelarInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarInButtonMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(64, 64, 64));
        jLabel10.setText("Trabajador:");

        trabajadoresCombo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        trabajadoresCombo.setNextFocusableComponent(userIButtton);

        permisosCombo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        permisosCombo.setNextFocusableComponent(trabajadoresCombo);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(64, 64, 64));
        jLabel11.setText("Nivel de Acceso:");

        javax.swing.GroupLayout ingresarPanelLayout = new javax.swing.GroupLayout(ingresarPanel);
        ingresarPanel.setLayout(ingresarPanelLayout);
        ingresarPanelLayout.setHorizontalGroup(
            ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarPanelLayout.createSequentialGroup()
                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ingresarPanelLayout.createSequentialGroup()
                                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passIField2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(passIField)
                                    .addComponent(userIField)
                                    .addComponent(permisosCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(ingresarPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(102, 102, 102)
                                .addComponent(trabajadoresCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)))
                    .addGroup(ingresarPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(userIButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(cancelarInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ingresarPanelLayout.setVerticalGroup(
            ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(userIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passIField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(permisosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(trabajadoresCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(ingresarPanel);
        ingresarPanel.setBounds(30, 250, 430, 230);

        usuariosPanel1.setOpaque(false);

        pn_herramientas2.setBackground(new java.awt.Color(96, 96, 96));
        pn_herramientas2.setPreferredSize(new java.awt.Dimension(868, 40));
        pn_herramientas2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verUsInButton.setBackground(new java.awt.Color(96, 96, 96));
        verUsInButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        verUsInButton.setForeground(new java.awt.Color(255, 255, 255));
        verUsInButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verUsInButton.setText("INGRESO");
        verUsInButton.setOpaque(true);
        verUsInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verUsInButtonMouseClicked(evt);
            }
        });
        pn_herramientas2.add(verUsInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        verUsModButton.setBackground(new java.awt.Color(96, 96, 96));
        verUsModButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        verUsModButton.setForeground(new java.awt.Color(255, 255, 255));
        verUsModButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verUsModButton.setText("MODIFICACIÓN");
        verUsModButton.setOpaque(true);
        verUsModButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verUsModButtonMouseClicked(evt);
            }
        });
        pn_herramientas2.add(verUsModButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 170, 40));

        verUsElButton.setBackground(new java.awt.Color(96, 96, 96));
        verUsElButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        verUsElButton.setForeground(new java.awt.Color(255, 255, 255));
        verUsElButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verUsElButton.setText("ELIMINACIÓN");
        verUsElButton.setOpaque(true);
        verUsElButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verUsElButtonMouseClicked(evt);
            }
        });
        pn_herramientas2.add(verUsElButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 0, 180, 40));

        javax.swing.GroupLayout usuariosPanel1Layout = new javax.swing.GroupLayout(usuariosPanel1);
        usuariosPanel1.setLayout(usuariosPanel1Layout);
        usuariosPanel1Layout.setHorizontalGroup(
            usuariosPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanel1Layout.createSequentialGroup()
                .addComponent(pn_herramientas2, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        usuariosPanel1Layout.setVerticalGroup(
            usuariosPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanel1Layout.createSequentialGroup()
                .addComponent(pn_herramientas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(usuariosPanel1);
        usuariosPanel1.setBounds(0, 40, 540, 40);

        modificarPanel.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(64, 64, 64));
        jLabel12.setText("Usuario:");

        usuariosMCombo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        usuariosMCombo.setNextFocusableComponent(permisosMCombo);
        usuariosMCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usuariosMComboItemStateChanged(evt);
            }
        });

        cambiarMButton.setBackground(new java.awt.Color(255, 51, 51));
        cambiarMButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cambiarMButton.setForeground(new java.awt.Color(255, 255, 255));
        cambiarMButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambiarMButton.setText("Cambiar");
        cambiarMButton.setOpaque(true);
        cambiarMButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiarMButtonMouseClicked(evt);
            }
        });

        cancelarMButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelarMButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cancelarMButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarMButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarMButton.setText("Cancelar");
        cancelarMButton.setOpaque(true);
        cancelarMButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMButtonMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 64, 64));
        jLabel13.setText("Nivel de Acceso:");

        permisosMCombo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        permisosMCombo.setNextFocusableComponent(cambiarMButton);

        javax.swing.GroupLayout modificarPanelLayout = new javax.swing.GroupLayout(modificarPanel);
        modificarPanel.setLayout(modificarPanelLayout);
        modificarPanelLayout.setHorizontalGroup(
            modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(cambiarMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuariosMCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(permisosMCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(modificarPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(cancelarMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        modificarPanelLayout.setVerticalGroup(
            modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(usuariosMCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(permisosMCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        add(modificarPanel);
        modificarPanel.setBounds(20, 490, 370, 150);

        pn_herramientas1.setBackground(new java.awt.Color(96, 96, 96));
        pn_herramientas1.setPreferredSize(new java.awt.Dimension(868, 40));
        pn_herramientas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(96, 96, 96));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/cancel (2).png"))); // NOI18N
        Salir.setOpaque(true);
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        pn_herramientas1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 40, 40));

        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSCE/minus-symbol.png"))); // NOI18N
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        pn_herramientas1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        gesUsuariosButton.setBackground(new java.awt.Color(96, 96, 96));
        gesUsuariosButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        gesUsuariosButton.setForeground(new java.awt.Color(255, 255, 255));
        gesUsuariosButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gesUsuariosButton.setText("USUARIOS");
        gesUsuariosButton.setOpaque(true);
        gesUsuariosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gesUsuariosButtonMouseClicked(evt);
            }
        });
        pn_herramientas1.add(gesUsuariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        gesConButton.setBackground(new java.awt.Color(96, 96, 96));
        gesConButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        gesConButton.setForeground(new java.awt.Color(255, 255, 255));
        gesConButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gesConButton.setText("CONEXIÓN");
        gesConButton.setOpaque(true);
        gesConButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gesConButtonMouseClicked(evt);
            }
        });
        pn_herramientas1.add(gesConButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 200, 40));

        logoutButton.setBackground(new java.awt.Color(96, 96, 96));
        logoutButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutButton.setText("LOG OUT");
        logoutButton.setOpaque(true);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        pn_herramientas1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 170, 40));

        add(pn_herramientas1);
        pn_herramientas1.setBounds(0, 0, 940, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void guardarDBButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarDBButtonMouseClicked
       if(!ipField.getText().trim().equals("")&&!userField.getText().trim().equals("")&&!new String(passField.getPassword()).trim().equals("")&&!bdField.getText().equals("")){
            if(new String(passField.getPassword()).trim().equals(new String(passField1.getPassword()).trim())){
                try {
                    // Generamos una clave que queramos que tenga al menos 16 bytes adecuada para AES
                    Key key = new SecretKeySpec(claveCifrado.getBytes(),  0, 16, "AES");
                    // Se obtiene un cifrador AES
                    Cipher aes = Cipher.getInstance("AES/ECB/PKCS5Padding");
                    // Se inicializa el cifrador, se pone en modo de cifrado y se le envia la clave
                    aes.init(Cipher.ENCRYPT_MODE,key);
                    // Se encripta
                    byte[] encriptado=aes.doFinal(new String(passField.getPassword()).getBytes());
                    //Se crea un nuevo servidor, enviando los datos nuevos y se escribe la configuracion al archivo
                    Server server=new Server(ipField.getText(), userField.getText(),encriptado , bdField.getText());
                    server.escribirArchivo(Server.SERVER_CONFIG_DEFAULT_FILE);
                    DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_INFORMACION, "Escritura exitosa", "Archivo Escrito");  
                    dialogo.setVisible(true);
                    //Limpiamos el formulario
                    limpiar();
                } catch (NoSePuedeEscribirArchivo | NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IllegalBlockSizeException | BadPaddingException ex) {
                    DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Escritura exitosa", ex.toString());  
                    dialogo.setVisible(true);
                }
            }
            else{
                DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Llene los campos correctamente", "Las contraseñas no coinciden");  
                dialogo.setVisible(true);
                passField.setText("");
                passField1.setText("");
                passField.requestFocus();
            }
        }
        else{
            DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Debe llenar todos los campos");
            dialogo.setVisible(true);
        }
    }//GEN-LAST:event_guardarDBButtonMouseClicked

    private void userEButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userEButtonMouseClicked
        eliminarUser();
    }//GEN-LAST:event_userEButtonMouseClicked

    private void userIButttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIButttonMouseClicked
        ingresoUserNuevo();
    }//GEN-LAST:event_userIButttonMouseClicked

    private void verUsElButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verUsElButtonMouseClicked
        try {
            verUsInButton.setBackground(color_reset);
            verUsElButton.setBackground(color_set);
            verUsModButton.setBackground(color_reset);
            //Limpiamos la lista de usuarios en el combo
            int tamano=usuariosCombo1.getModel().getSize();
            for (int i = 0; i < tamano; i++) {
                usuariosCombo1.removeItemAt(0);
            }
            //Obtenemos la lista de usuarios desde la BD, y luego los agregamos al combo
            ArrayList modelo= conexion.obtenerUsuarios();
            for(int i=0;i<modelo.size();i++){
                usuariosCombo1.addItem((String) modelo.get(i));
            }
            //Hacemos que no esté seleccionado ningún elemento del combo, y mostramos el panel
            usuariosCombo1.setSelectedIndex(-1);
            eliminarPanel.setVisible(true);
            usuariosPanel1.setVisible(false);
            gesUsuariosButton.setEnabled(false);
        } catch (SQLException|NoSePuedeConectar ex) {
            DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Error:\n"+ex.toString());
            dialogo.setVisible(true);
        }
    }//GEN-LAST:event_verUsElButtonMouseClicked

    private void verUsInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verUsInButtonMouseClicked
        try {
            limpiar();
            verUsInButton.setBackground(color_set);
            verUsElButton.setBackground(color_reset);
            verUsModButton.setBackground(color_reset);
            ingresarPanel.setVisible(true);
            usuariosPanel1.setVisible(false);
            ArrayList trabajadores=conexion.obtenerTrabajadoresParaUsuarios();
            for (int i = 0; i < trabajadores.size(); i++) {
                trabajadoresCombo.addItem(trabajadores.get(i).toString());
            }
            ArrayList permisos=conexion.obtenerPermisos();
            for (int i = 0; i < permisos.size(); i++) {
                permisosCombo.addItem(permisos.get(i).toString());
            }
            permisosCombo.setSelectedIndex(-1);
            trabajadoresCombo.setSelectedIndex(-1);
            gesUsuariosButton.setEnabled(false);
        } catch (NoSePuedeConectar|SQLException ex) {
            DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Ingreso", "Error:\n"+ex.toString());
            dialogo.setVisible(true);
        }
        
    }//GEN-LAST:event_verUsInButtonMouseClicked

    private void cancelarInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarInButtonMouseClicked
        limpiar();
    }//GEN-LAST:event_cancelarInButtonMouseClicked

    private void cancelarGesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarGesButtonMouseClicked
        limpiar();
    }//GEN-LAST:event_cancelarGesButtonMouseClicked

    private void cancelarElButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarElButtonMouseClicked
        limpiar();
    }//GEN-LAST:event_cancelarElButtonMouseClicked

    private void probarDBButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_probarDBButtonMouseClicked
        if(!ipField.getText().trim().equals("")&&!userField.getText().trim().equals("")&&!new String(passField.getPassword()).trim().equals("")&&!bdField.getText().equals("")){
            if(new String(passField.getPassword()).trim().equals(new String(passField1.getPassword()).trim())){
                Base prueba= new Base(userField.getText(), ipField.getText(), new String(passField.getPassword()),bdField.getText());
                if(prueba.probarConexion()){
                    DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_INFORMACION, "Conexión exitosa", "Esta configuración es correcta\nSe puede conectar al SGBD");  
                    dialogo.setVisible(true);
                }else{
                    DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Conexión fallida", "Esta configuración es incorrecta\nNo se puede conectar al SGBD");  
                    dialogo.setVisible(true);
                }
            }else{
                DialogoOpcion dialogo = new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Llene los campos correctamente", "Las contraseñas no coinciden");  
                dialogo.setVisible(true);
                passField.setText("");
                passField1.setText("");
                passField.requestFocus();
            }
        }
        
    }//GEN-LAST:event_probarDBButtonMouseClicked

    private void cambiarMButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarMButtonMouseClicked
        try{
            if(usuariosMCombo.getSelectedIndex()>-1){
                DialogoOpcion dialogo= new DialogoOpcion(null,true,DialogoOpcion.ICONO_INTERROGANTE,"Modificar usuario","¿Está seguro de modificar el usuario "+usuariosMCombo.getSelectedItem().toString()+"?");
                dialogo.setVisible(true);
                if(dialogo.isAceptar()){
                    //Manda la orden de eliminación a la BD, devuelve el número de filas cambiadas
                        int filasMod=conexion.modificacionUsuario(usuariosMCombo.getSelectedItem().toString(),permisosMCombo.getSelectedIndex()+1);
                        dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_INFORMACION, "Eliminación", "Se ha eliminado la sucursal\nRegistros actualizados: "+filasMod);
                        dialogo.setVisible(true);
                        //Limpia el formulario
                        limpiar();
                }
            }
        } catch (SQLException|NoSePuedeConectar ex) {
            DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Error:\n"+ex.toString());
            dialogo.setVisible(true);
        }
    }//GEN-LAST:event_cambiarMButtonMouseClicked

    private void cancelarMButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMButtonMouseClicked
        limpiar();
    }//GEN-LAST:event_cancelarMButtonMouseClicked

    private void verUsModButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verUsModButtonMouseClicked
        try {
            verUsInButton.setBackground(color_reset);
            verUsElButton.setBackground(color_reset);
            verUsModButton.setBackground(color_set);
            //Limpiamos la lista de usuarios en el combo
            int tamano=usuariosMCombo.getModel().getSize();
            for (int i = 0; i < tamano; i++) {
                usuariosMCombo.removeItemAt(0);
            }
            //Obtenemos la lista de usuarios desde la BD, y luego los agregamos al combo
            ArrayList modelo= conexion.obtenerUsuarios();
            for(int i=0;i<modelo.size();i++){
                usuariosMCombo.addItem((String) modelo.get(i));
            }
            ArrayList permisos=conexion.obtenerPermisos();
            for (int i = 0; i < permisos.size(); i++) {
                permisosMCombo.addItem(permisos.get(i).toString());
            }
            //Hacemos que no esté seleccionado ningún elemento de los combos, y mostramos el panel
            usuariosMCombo.setSelectedIndex(-1);
            permisosMCombo.setSelectedIndex(-1);
            modificarPanel.setVisible(true);
            usuariosPanel1.setVisible(false);
            gesUsuariosButton.setEnabled(false);
        } catch (SQLException|NoSePuedeConectar ex) {
            DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Error:\n"+ex.toString());
            dialogo.setVisible(true);
        }
    }//GEN-LAST:event_verUsModButtonMouseClicked

    private void usuariosMComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usuariosMComboItemStateChanged
        if(permisosMCombo.getModel().getSize()>0&&usuariosMCombo.getSelectedIndex()>-1){
            try {
                permisosMCombo.setSelectedIndex(conexion.obtenerPermisosDeUsuario(usuariosMCombo.getSelectedItem().toString())-1);
            } catch (SQLException|NoSePuedeConectar ex) {
                DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Error:\n"+ex.toString());
                dialogo.setVisible(true);
            }
        }
    }//GEN-LAST:event_usuariosMComboItemStateChanged

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        //Borramos el contenido del archivo de logueo, para que no vuelva a iniciarse la sesión
        BufferedWriter bw = null;
        try {
            bw = new BufferedWriter(new FileWriter(UsuarioG.LOGGED_USER_DEFAULT_FILE));
            bw.write("");
            bw.close();
        } catch (IOException ex) {
            DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Error:\n"+ex.toString());
            dialogo.setVisible(true);
        } finally {
            try {
                bw.close();
            } catch (IOException ex) {
                DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Error:\n"+ex.toString());
                dialogo.setVisible(true);
            }
        }
        // (Comentar/Descomentar una opción) Despues de borrar el archivo, mostramos de nuevo la ventana de login, o cerramos el programa
        //Opcion 1: cierra el programa
        System.exit(0);
        //Opcion 2: muestra de nuevo el login (aun infuncional)
        //Login l= new Login();
        //this.setVisible(false);
        //l.setVisible(true);

    }//GEN-LAST:event_logoutButtonMouseClicked

    private void gesConButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gesConButtonMouseClicked
        if(gesConButton.isEnabled()){
            conexionPanel.setVisible(true);
            gesUsuariosButton.setBackground(color_reset);
            gesConButton.setBackground(color_set);
            gesUsuariosButton.setEnabled(false);
        }
    }//GEN-LAST:event_gesConButtonMouseClicked

    private void gesUsuariosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gesUsuariosButtonMouseClicked
        if(gesUsuariosButton.isEnabled()){
            //Mostramos el panel de gestión de usuarios, y deshabilitamos otras opciones
            usuariosPanel1.setVisible(true);
            gesUsuariosButton.setBackground(color_set);
            gesConButton.setBackground(color_reset);
            gesConButton.setEnabled(false);
        }
    }//GEN-LAST:event_gesUsuariosButtonMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        //Obtenemos los contenedores padres, hasta obtener el JFrame donde se está trabajando
        JFrame padre= (JFrame)this.getParent().getParent().getParent().getParent().getParent();
        //Se le manda la orden de minimizar
        padre.setExtendedState(1);
    }//GEN-LAST:event_MinimizarMouseClicked
    //Elimina un usuario, seleccionado en el combo
    private void eliminarUser(){
        //Verifica que haya un objeto seleccionado en el combo
        if(usuariosCombo1.getSelectedIndex()!=-1){
            DialogoOpcion diag= new DialogoOpcion(null,true,DialogoOpcion.ICONO_INTERROGANTE,"Eliminar usuario","¿Está seguro de eliminar el usuario "+usuariosCombo1.getSelectedItem().toString()+"?");
            diag.setVisible(true);
            if(diag.isAceptar()){
                try {
                    //Manda la orden de eliminación a la BD
                    conexion.eliminarUsuario((String) usuariosCombo1.getSelectedItem());
                    //Muestra mensaje de borrado, y pone todo en estado normal
                    diag= new DialogoOpcion(null,true,DialogoOpcion.ICONO_INFORMACION,"Eliminar usuario","Usuario eliminado");
                    diag.setVisible(true);
                    limpiar();
                } catch (SQLException|NoSePuedeConectar ex) {
                    DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Error:\n"+ex.toString());
                    dialogo.setVisible(true);
                }
            }
            limpiar();
        }
    }
    /**
     * Ingresa un usuario nuevo
     */
    private void ingresoUserNuevo(){
        //Obtiene las Strings en los campos de contraseña
        String pass1=new String(passIField.getPassword()),pass2=new String(passIField2.getPassword());
        //Obtiene el nombre del usuario
        String user=userIField.getText();
        //Compara que las contraseñas sean iguales
        if(!user.equals("")&&pass1.equals(pass2)&&!pass1.equals("")&&permisosCombo.getSelectedIndex()>-1){
            try {
                int idTrabajador=0;
                if(trabajadoresCombo.getSelectedIndex()!=-1){
                    //Obtenemos el ID del trabajador
                    String[] trabajadorSeparado=trabajadoresCombo.getSelectedItem().toString().split("-");
                    idTrabajador=Integer.parseInt(trabajadorSeparado[trabajadorSeparado.length-1]);
                }
                //Manda la orden de ingreso de usuario, si la función retorna 1 significa que se ingresó correctamente
                if(conexion.crearUsuario(user, pass1,idTrabajador,(permisosCombo.getSelectedIndex()+1))==1){
                    //Muestra un mensaje de exito, y limpia
                    DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_INFORMACION, "Ingreso", "Ingreso exitoso");
                    dialogo.setVisible(true);
                    passIField.setText("");
                    passIField2.setText("");
                    userIField.setText("");
                    limpiar();
                }
                else{
                    DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Ingreso", "Este usuario ya existe");
                    dialogo.setVisible(true);
                    passIField.setText("");
                    passIField2.setText("");
                    userIField.setText("");
                    userIField.requestFocus();
                }
            } catch (SQLException|NoSePuedeConectar ex) {
                DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Error:\n"+ex.toString());
                dialogo.setVisible(true);
            }
        }else{
            DialogoOpcion dialogo= new DialogoOpcion(null, true, DialogoOpcion.ICONO_ERROR, "Error", "Ingrese los datos adecuadamente");
            dialogo.setVisible(true);
        }
    }
    /**
     * Limpia el JPanel para poner los paneles no usados invisibles
     */
    private void limpiar(){
        eliminarPanel.setVisible(false);
        modificarPanel.setVisible(false);
        ingresarPanel.setVisible(false);
        conexionPanel.setVisible(false);
        usuariosPanel1.setVisible(false);
        ingresarPanel.setBounds(eliminarPanel.getBounds().x, eliminarPanel.getBounds().y, ingresarPanel.getBounds().width, ingresarPanel.getBounds().height);
        conexionPanel.setBounds(eliminarPanel.getBounds().x, eliminarPanel.getBounds().y,conexionPanel.getBounds().width,conexionPanel.getBounds().height);
        modificarPanel.setBounds(eliminarPanel.getBounds().x, eliminarPanel.getBounds().y,modificarPanel.getBounds().width,modificarPanel.getBounds().height);
        gesConButton.setEnabled(true);
        gesUsuariosButton.setEnabled(true);
        //Limpiamos los campos de texto
        ipField.setText("");
        userField.setText("");
        passField.setText("");
        passField1.setText("");
        bdField.setText("");
        int tamano=permisosCombo.getModel().getSize();
        for (int i = 0; i < tamano; i++) {
            permisosCombo.removeItemAt(0);
        }
        tamano=trabajadoresCombo.getModel().getSize();
        for (int i = 0; i < tamano; i++) {
            trabajadoresCombo.removeItemAt(0);
        }
        tamano=permisosMCombo.getModel().getSize();
        for (int i = 0; i < tamano; i++) {
            permisosMCombo.removeItemAt(0);
        }
        tamano=usuariosMCombo.getModel().getSize();
        for (int i = 0; i < tamano; i++) {
            usuariosMCombo.removeItemAt(0);
        }
        tamano=usuariosCombo1.getModel().getSize();
        for (int i = 0; i < tamano; i++) {
            usuariosCombo1.removeItemAt(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel Salir;
    private javax.swing.JTextField bdField;
    private javax.swing.JLabel cambiarMButton;
    private javax.swing.JLabel cancelarElButton;
    private javax.swing.JLabel cancelarGesButton;
    private javax.swing.JLabel cancelarInButton;
    private javax.swing.JLabel cancelarMButton;
    private javax.swing.JPanel conexionPanel;
    private javax.swing.JPanel eliminarPanel;
    private javax.swing.JLabel gesConButton;
    private javax.swing.JLabel gesUsuariosButton;
    private javax.swing.JLabel guardarDBButton;
    private javax.swing.JPanel ingresarPanel;
    private javax.swing.JTextField ipField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JPanel modificarPanel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JPasswordField passField1;
    private javax.swing.JPasswordField passIField;
    private javax.swing.JPasswordField passIField2;
    private javax.swing.JComboBox<String> permisosCombo;
    private javax.swing.JComboBox<String> permisosMCombo;
    private javax.swing.JPanel pn_herramientas1;
    private javax.swing.JPanel pn_herramientas2;
    private javax.swing.JLabel probarDBButton;
    private javax.swing.JComboBox<String> trabajadoresCombo;
    private javax.swing.JLabel userEButton;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userIButtton;
    private javax.swing.JTextField userIField;
    private javax.swing.JComboBox<String> usuariosCombo1;
    private javax.swing.JComboBox<String> usuariosMCombo;
    private javax.swing.JPanel usuariosPanel1;
    private javax.swing.JLabel verUsElButton;
    private javax.swing.JLabel verUsInButton;
    private javax.swing.JLabel verUsModButton;
    // End of variables declaration//GEN-END:variables
}
